// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/yarn_server_resourcemanager_service_protos.proto

/*
Package hadoop_yarn is a generated protocol buffer package.

It is generated from these files:
	server/yarn_server_resourcemanager_service_protos.proto

It has these top-level messages:
	RefreshQueuesRequestProto
	RefreshQueuesResponseProto
	RefreshNodesRequestProto
	RefreshNodesResponseProto
	RefreshSuperUserGroupsConfigurationRequestProto
	RefreshSuperUserGroupsConfigurationResponseProto
	RefreshUserToGroupsMappingsRequestProto
	RefreshUserToGroupsMappingsResponseProto
	RefreshAdminAclsRequestProto
	RefreshAdminAclsResponseProto
	RefreshServiceAclsRequestProto
	RefreshServiceAclsResponseProto
	GetGroupsForUserRequestProto
	GetGroupsForUserResponseProto
	UpdateNodeResourceRequestProto
	UpdateNodeResourceResponseProto
	AddToClusterNodeLabelsRequestProto
	AddToClusterNodeLabelsResponseProto
	RemoveFromClusterNodeLabelsRequestProto
	RemoveFromClusterNodeLabelsResponseProto
	ReplaceLabelsOnNodeRequestProto
	ReplaceLabelsOnNodeResponseProto
	UpdateNodeLabelsResponseProto
	CheckForDecommissioningNodesRequestProto
	CheckForDecommissioningNodesResponseProto
	NodeIdToLabelsNameProto
	ActiveRMInfoProto
*/
package hadoop_yarn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DecommissionTypeProto int32

const (
	DecommissionTypeProto_NORMAL   DecommissionTypeProto = 1
	DecommissionTypeProto_GRACEFUL DecommissionTypeProto = 2
	DecommissionTypeProto_FORCEFUL DecommissionTypeProto = 3
)

var DecommissionTypeProto_name = map[int32]string{
	1: "NORMAL",
	2: "GRACEFUL",
	3: "FORCEFUL",
}
var DecommissionTypeProto_value = map[string]int32{
	"NORMAL":   1,
	"GRACEFUL": 2,
	"FORCEFUL": 3,
}

func (x DecommissionTypeProto) Enum() *DecommissionTypeProto {
	p := new(DecommissionTypeProto)
	*p = x
	return p
}
func (x DecommissionTypeProto) String() string {
	return proto.EnumName(DecommissionTypeProto_name, int32(x))
}
func (x *DecommissionTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DecommissionTypeProto_value, data, "DecommissionTypeProto")
	if err != nil {
		return err
	}
	*x = DecommissionTypeProto(value)
	return nil
}
func (DecommissionTypeProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RefreshQueuesRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshQueuesRequestProto) Reset()                    { *m = RefreshQueuesRequestProto{} }
func (m *RefreshQueuesRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshQueuesRequestProto) ProtoMessage()               {}
func (*RefreshQueuesRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RefreshQueuesResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshQueuesResponseProto) Reset()                    { *m = RefreshQueuesResponseProto{} }
func (m *RefreshQueuesResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshQueuesResponseProto) ProtoMessage()               {}
func (*RefreshQueuesResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RefreshNodesRequestProto struct {
	DecommissionType *DecommissionTypeProto `protobuf:"varint,1,opt,name=decommissionType,enum=hadoop.yarn.DecommissionTypeProto,def=1" json:"decommissionType,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *RefreshNodesRequestProto) Reset()                    { *m = RefreshNodesRequestProto{} }
func (m *RefreshNodesRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshNodesRequestProto) ProtoMessage()               {}
func (*RefreshNodesRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_RefreshNodesRequestProto_DecommissionType DecommissionTypeProto = DecommissionTypeProto_NORMAL

func (m *RefreshNodesRequestProto) GetDecommissionType() DecommissionTypeProto {
	if m != nil && m.DecommissionType != nil {
		return *m.DecommissionType
	}
	return Default_RefreshNodesRequestProto_DecommissionType
}

type RefreshNodesResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshNodesResponseProto) Reset()                    { *m = RefreshNodesResponseProto{} }
func (m *RefreshNodesResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshNodesResponseProto) ProtoMessage()               {}
func (*RefreshNodesResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RefreshSuperUserGroupsConfigurationRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshSuperUserGroupsConfigurationRequestProto) Reset() {
	*m = RefreshSuperUserGroupsConfigurationRequestProto{}
}
func (m *RefreshSuperUserGroupsConfigurationRequestProto) String() string {
	return proto.CompactTextString(m)
}
func (*RefreshSuperUserGroupsConfigurationRequestProto) ProtoMessage() {}
func (*RefreshSuperUserGroupsConfigurationRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

type RefreshSuperUserGroupsConfigurationResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshSuperUserGroupsConfigurationResponseProto) Reset() {
	*m = RefreshSuperUserGroupsConfigurationResponseProto{}
}
func (m *RefreshSuperUserGroupsConfigurationResponseProto) String() string {
	return proto.CompactTextString(m)
}
func (*RefreshSuperUserGroupsConfigurationResponseProto) ProtoMessage() {}
func (*RefreshSuperUserGroupsConfigurationResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

type RefreshUserToGroupsMappingsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshUserToGroupsMappingsRequestProto) Reset() {
	*m = RefreshUserToGroupsMappingsRequestProto{}
}
func (m *RefreshUserToGroupsMappingsRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshUserToGroupsMappingsRequestProto) ProtoMessage()    {}
func (*RefreshUserToGroupsMappingsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

type RefreshUserToGroupsMappingsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshUserToGroupsMappingsResponseProto) Reset() {
	*m = RefreshUserToGroupsMappingsResponseProto{}
}
func (m *RefreshUserToGroupsMappingsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshUserToGroupsMappingsResponseProto) ProtoMessage()    {}
func (*RefreshUserToGroupsMappingsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

type RefreshAdminAclsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshAdminAclsRequestProto) Reset()                    { *m = RefreshAdminAclsRequestProto{} }
func (m *RefreshAdminAclsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshAdminAclsRequestProto) ProtoMessage()               {}
func (*RefreshAdminAclsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RefreshAdminAclsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshAdminAclsResponseProto) Reset()                    { *m = RefreshAdminAclsResponseProto{} }
func (m *RefreshAdminAclsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshAdminAclsResponseProto) ProtoMessage()               {}
func (*RefreshAdminAclsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type RefreshServiceAclsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshServiceAclsRequestProto) Reset()                    { *m = RefreshServiceAclsRequestProto{} }
func (m *RefreshServiceAclsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshServiceAclsRequestProto) ProtoMessage()               {}
func (*RefreshServiceAclsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type RefreshServiceAclsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshServiceAclsResponseProto) Reset()         { *m = RefreshServiceAclsResponseProto{} }
func (m *RefreshServiceAclsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshServiceAclsResponseProto) ProtoMessage()    {}
func (*RefreshServiceAclsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11}
}

type GetGroupsForUserRequestProto struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetGroupsForUserRequestProto) Reset()                    { *m = GetGroupsForUserRequestProto{} }
func (m *GetGroupsForUserRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetGroupsForUserRequestProto) ProtoMessage()               {}
func (*GetGroupsForUserRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetGroupsForUserRequestProto) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

type GetGroupsForUserResponseProto struct {
	Groups           []string `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetGroupsForUserResponseProto) Reset()                    { *m = GetGroupsForUserResponseProto{} }
func (m *GetGroupsForUserResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetGroupsForUserResponseProto) ProtoMessage()               {}
func (*GetGroupsForUserResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetGroupsForUserResponseProto) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type UpdateNodeResourceRequestProto struct {
	NodeResourceMap  []*NodeResourceMapProto `protobuf:"bytes,1,rep,name=node_resource_map,json=nodeResourceMap" json:"node_resource_map,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UpdateNodeResourceRequestProto) Reset()                    { *m = UpdateNodeResourceRequestProto{} }
func (m *UpdateNodeResourceRequestProto) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeResourceRequestProto) ProtoMessage()               {}
func (*UpdateNodeResourceRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UpdateNodeResourceRequestProto) GetNodeResourceMap() []*NodeResourceMapProto {
	if m != nil {
		return m.NodeResourceMap
	}
	return nil
}

type UpdateNodeResourceResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateNodeResourceResponseProto) Reset()         { *m = UpdateNodeResourceResponseProto{} }
func (m *UpdateNodeResourceResponseProto) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeResourceResponseProto) ProtoMessage()    {}
func (*UpdateNodeResourceResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15}
}

type AddToClusterNodeLabelsRequestProto struct {
	NodeLabels       []*NodeLabelProto `protobuf:"bytes,1,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *AddToClusterNodeLabelsRequestProto) Reset()         { *m = AddToClusterNodeLabelsRequestProto{} }
func (m *AddToClusterNodeLabelsRequestProto) String() string { return proto.CompactTextString(m) }
func (*AddToClusterNodeLabelsRequestProto) ProtoMessage()    {}
func (*AddToClusterNodeLabelsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16}
}

func (m *AddToClusterNodeLabelsRequestProto) GetNodeLabels() []*NodeLabelProto {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

type AddToClusterNodeLabelsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AddToClusterNodeLabelsResponseProto) Reset()         { *m = AddToClusterNodeLabelsResponseProto{} }
func (m *AddToClusterNodeLabelsResponseProto) String() string { return proto.CompactTextString(m) }
func (*AddToClusterNodeLabelsResponseProto) ProtoMessage()    {}
func (*AddToClusterNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17}
}

type RemoveFromClusterNodeLabelsRequestProto struct {
	NodeLabels       []string `protobuf:"bytes,1,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RemoveFromClusterNodeLabelsRequestProto) Reset() {
	*m = RemoveFromClusterNodeLabelsRequestProto{}
}
func (m *RemoveFromClusterNodeLabelsRequestProto) String() string { return proto.CompactTextString(m) }
func (*RemoveFromClusterNodeLabelsRequestProto) ProtoMessage()    {}
func (*RemoveFromClusterNodeLabelsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18}
}

func (m *RemoveFromClusterNodeLabelsRequestProto) GetNodeLabels() []string {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

type RemoveFromClusterNodeLabelsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveFromClusterNodeLabelsResponseProto) Reset() {
	*m = RemoveFromClusterNodeLabelsResponseProto{}
}
func (m *RemoveFromClusterNodeLabelsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RemoveFromClusterNodeLabelsResponseProto) ProtoMessage()    {}
func (*RemoveFromClusterNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19}
}

type ReplaceLabelsOnNodeRequestProto struct {
	NodeToLabels     []*NodeIdToLabelsNameProto `protobuf:"bytes,1,rep,name=nodeToLabels" json:"nodeToLabels,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ReplaceLabelsOnNodeRequestProto) Reset()         { *m = ReplaceLabelsOnNodeRequestProto{} }
func (m *ReplaceLabelsOnNodeRequestProto) String() string { return proto.CompactTextString(m) }
func (*ReplaceLabelsOnNodeRequestProto) ProtoMessage()    {}
func (*ReplaceLabelsOnNodeRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{20}
}

func (m *ReplaceLabelsOnNodeRequestProto) GetNodeToLabels() []*NodeIdToLabelsNameProto {
	if m != nil {
		return m.NodeToLabels
	}
	return nil
}

type ReplaceLabelsOnNodeResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReplaceLabelsOnNodeResponseProto) Reset()         { *m = ReplaceLabelsOnNodeResponseProto{} }
func (m *ReplaceLabelsOnNodeResponseProto) String() string { return proto.CompactTextString(m) }
func (*ReplaceLabelsOnNodeResponseProto) ProtoMessage()    {}
func (*ReplaceLabelsOnNodeResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{21}
}

type UpdateNodeLabelsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateNodeLabelsResponseProto) Reset()                    { *m = UpdateNodeLabelsResponseProto{} }
func (m *UpdateNodeLabelsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeLabelsResponseProto) ProtoMessage()               {}
func (*UpdateNodeLabelsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type CheckForDecommissioningNodesRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CheckForDecommissioningNodesRequestProto) Reset() {
	*m = CheckForDecommissioningNodesRequestProto{}
}
func (m *CheckForDecommissioningNodesRequestProto) String() string { return proto.CompactTextString(m) }
func (*CheckForDecommissioningNodesRequestProto) ProtoMessage()    {}
func (*CheckForDecommissioningNodesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{23}
}

type CheckForDecommissioningNodesResponseProto struct {
	DecommissioningNodes []*NodeIdProto `protobuf:"bytes,1,rep,name=decommissioningNodes" json:"decommissioningNodes,omitempty"`
	XXX_unrecognized     []byte         `json:"-"`
}

func (m *CheckForDecommissioningNodesResponseProto) Reset() {
	*m = CheckForDecommissioningNodesResponseProto{}
}
func (m *CheckForDecommissioningNodesResponseProto) String() string { return proto.CompactTextString(m) }
func (*CheckForDecommissioningNodesResponseProto) ProtoMessage()    {}
func (*CheckForDecommissioningNodesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{24}
}

func (m *CheckForDecommissioningNodesResponseProto) GetDecommissioningNodes() []*NodeIdProto {
	if m != nil {
		return m.DecommissioningNodes
	}
	return nil
}

type NodeIdToLabelsNameProto struct {
	NodeId           *NodeIdProto `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
	NodeLabels       []string     `protobuf:"bytes,2,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NodeIdToLabelsNameProto) Reset()                    { *m = NodeIdToLabelsNameProto{} }
func (m *NodeIdToLabelsNameProto) String() string            { return proto.CompactTextString(m) }
func (*NodeIdToLabelsNameProto) ProtoMessage()               {}
func (*NodeIdToLabelsNameProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *NodeIdToLabelsNameProto) GetNodeId() *NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *NodeIdToLabelsNameProto) GetNodeLabels() []string {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

// ////////////////////////////////////////////////////////////////
// /////////// RM Failover related records ////////////////////////
// ////////////////////////////////////////////////////////////////
type ActiveRMInfoProto struct {
	ClusterId        *string `protobuf:"bytes,1,opt,name=clusterId" json:"clusterId,omitempty"`
	RmId             *string `protobuf:"bytes,2,opt,name=rmId" json:"rmId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ActiveRMInfoProto) Reset()                    { *m = ActiveRMInfoProto{} }
func (m *ActiveRMInfoProto) String() string            { return proto.CompactTextString(m) }
func (*ActiveRMInfoProto) ProtoMessage()               {}
func (*ActiveRMInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ActiveRMInfoProto) GetClusterId() string {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return ""
}

func (m *ActiveRMInfoProto) GetRmId() string {
	if m != nil && m.RmId != nil {
		return *m.RmId
	}
	return ""
}

func init() {
	proto.RegisterType((*RefreshQueuesRequestProto)(nil), "hadoop.yarn.RefreshQueuesRequestProto")
	proto.RegisterType((*RefreshQueuesResponseProto)(nil), "hadoop.yarn.RefreshQueuesResponseProto")
	proto.RegisterType((*RefreshNodesRequestProto)(nil), "hadoop.yarn.RefreshNodesRequestProto")
	proto.RegisterType((*RefreshNodesResponseProto)(nil), "hadoop.yarn.RefreshNodesResponseProto")
	proto.RegisterType((*RefreshSuperUserGroupsConfigurationRequestProto)(nil), "hadoop.yarn.RefreshSuperUserGroupsConfigurationRequestProto")
	proto.RegisterType((*RefreshSuperUserGroupsConfigurationResponseProto)(nil), "hadoop.yarn.RefreshSuperUserGroupsConfigurationResponseProto")
	proto.RegisterType((*RefreshUserToGroupsMappingsRequestProto)(nil), "hadoop.yarn.RefreshUserToGroupsMappingsRequestProto")
	proto.RegisterType((*RefreshUserToGroupsMappingsResponseProto)(nil), "hadoop.yarn.RefreshUserToGroupsMappingsResponseProto")
	proto.RegisterType((*RefreshAdminAclsRequestProto)(nil), "hadoop.yarn.RefreshAdminAclsRequestProto")
	proto.RegisterType((*RefreshAdminAclsResponseProto)(nil), "hadoop.yarn.RefreshAdminAclsResponseProto")
	proto.RegisterType((*RefreshServiceAclsRequestProto)(nil), "hadoop.yarn.RefreshServiceAclsRequestProto")
	proto.RegisterType((*RefreshServiceAclsResponseProto)(nil), "hadoop.yarn.RefreshServiceAclsResponseProto")
	proto.RegisterType((*GetGroupsForUserRequestProto)(nil), "hadoop.yarn.GetGroupsForUserRequestProto")
	proto.RegisterType((*GetGroupsForUserResponseProto)(nil), "hadoop.yarn.GetGroupsForUserResponseProto")
	proto.RegisterType((*UpdateNodeResourceRequestProto)(nil), "hadoop.yarn.UpdateNodeResourceRequestProto")
	proto.RegisterType((*UpdateNodeResourceResponseProto)(nil), "hadoop.yarn.UpdateNodeResourceResponseProto")
	proto.RegisterType((*AddToClusterNodeLabelsRequestProto)(nil), "hadoop.yarn.AddToClusterNodeLabelsRequestProto")
	proto.RegisterType((*AddToClusterNodeLabelsResponseProto)(nil), "hadoop.yarn.AddToClusterNodeLabelsResponseProto")
	proto.RegisterType((*RemoveFromClusterNodeLabelsRequestProto)(nil), "hadoop.yarn.RemoveFromClusterNodeLabelsRequestProto")
	proto.RegisterType((*RemoveFromClusterNodeLabelsResponseProto)(nil), "hadoop.yarn.RemoveFromClusterNodeLabelsResponseProto")
	proto.RegisterType((*ReplaceLabelsOnNodeRequestProto)(nil), "hadoop.yarn.ReplaceLabelsOnNodeRequestProto")
	proto.RegisterType((*ReplaceLabelsOnNodeResponseProto)(nil), "hadoop.yarn.ReplaceLabelsOnNodeResponseProto")
	proto.RegisterType((*UpdateNodeLabelsResponseProto)(nil), "hadoop.yarn.UpdateNodeLabelsResponseProto")
	proto.RegisterType((*CheckForDecommissioningNodesRequestProto)(nil), "hadoop.yarn.CheckForDecommissioningNodesRequestProto")
	proto.RegisterType((*CheckForDecommissioningNodesResponseProto)(nil), "hadoop.yarn.CheckForDecommissioningNodesResponseProto")
	proto.RegisterType((*NodeIdToLabelsNameProto)(nil), "hadoop.yarn.NodeIdToLabelsNameProto")
	proto.RegisterType((*ActiveRMInfoProto)(nil), "hadoop.yarn.ActiveRMInfoProto")
	proto.RegisterEnum("hadoop.yarn.DecommissionTypeProto", DecommissionTypeProto_name, DecommissionTypeProto_value)
}

func init() {
	proto.RegisterFile("server/yarn_server_resourcemanager_service_protos.proto", fileDescriptor8)
}

var fileDescriptor8 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x4f, 0xdb, 0x40,
	0x10, 0x95, 0x43, 0x85, 0x9a, 0x01, 0xb5, 0x60, 0xf5, 0x23, 0x85, 0x10, 0x82, 0xfb, 0x15, 0x38,
	0x04, 0x9a, 0x0b, 0x52, 0x7b, 0xa8, 0x42, 0x4a, 0x68, 0xa4, 0x04, 0x5a, 0x13, 0x2a, 0xf5, 0x14,
	0x6d, 0xed, 0x21, 0xb1, 0xc0, 0xbb, 0xdb, 0x5d, 0x1b, 0x89, 0x7f, 0xd0, 0x9f, 0xd1, 0x9f, 0x5a,
	0x79, 0xbd, 0xc0, 0x2e, 0x36, 0x51, 0x4f, 0xb1, 0xfd, 0x66, 0xde, 0x7b, 0x33, 0x3b, 0x99, 0x85,
	0x7d, 0x89, 0xe2, 0x0a, 0xc5, 0xee, 0x35, 0x11, 0x74, 0x92, 0x3f, 0x4f, 0x04, 0x4a, 0x96, 0x8a,
	0x00, 0x63, 0x42, 0xc9, 0x14, 0x85, 0xfa, 0x1c, 0x05, 0x38, 0xe1, 0x82, 0x25, 0x4c, 0xb6, 0xd5,
	0x8f, 0xbb, 0x34, 0x23, 0x21, 0x63, 0xbc, 0x9d, 0x25, 0xae, 0xad, 0xaa, 0x74, 0x13, 0xf7, 0xd6,
	0xe1, 0x95, 0x8f, 0xe7, 0x02, 0xe5, 0xec, 0x7b, 0x8a, 0x29, 0x4a, 0x1f, 0x7f, 0xa7, 0x28, 0x93,
	0x6f, 0x0a, 0xac, 0xc3, 0xda, 0x3d, 0x50, 0x72, 0x46, 0x25, 0xe6, 0xa8, 0x80, 0x9a, 0x46, 0x8f,
	0x59, 0x68, 0x67, 0xba, 0x3f, 0x60, 0x25, 0xc4, 0x80, 0xc5, 0x71, 0x24, 0x65, 0xc4, 0xe8, 0xf8,
	0x9a, 0x63, 0xcd, 0x69, 0x3a, 0xad, 0x27, 0x1d, 0xaf, 0x6d, 0x38, 0x6a, 0x7f, 0xb9, 0x17, 0xa4,
	0xb2, 0x3f, 0x2e, 0x1e, 0x9f, 0xf8, 0xa3, 0xee, 0xd0, 0x2f, 0x70, 0x18, 0x76, 0xb5, 0xa6, 0x69,
	0xe8, 0x03, 0xec, 0x6a, 0xf0, 0x34, 0xe5, 0x28, 0xce, 0x24, 0x8a, 0x23, 0xc1, 0x52, 0x2e, 0x7b,
	0x8c, 0x9e, 0x47, 0xd3, 0x54, 0x90, 0x24, 0x62, 0xd4, 0xaa, 0xb0, 0x03, 0x7b, 0xff, 0x95, 0x62,
	0xca, 0x6c, 0xc3, 0x7b, 0x9d, 0x93, 0x85, 0x8f, 0x59, 0x9e, 0x30, 0x22, 0x9c, 0x47, 0x74, 0x6a,
	0x37, 0x70, 0x07, 0x5a, 0x73, 0x43, 0x4d, 0xda, 0x06, 0xd4, 0x75, 0x6c, 0x37, 0x8c, 0x23, 0xda,
	0x0d, 0x2e, 0x6d, 0xae, 0x4d, 0xd8, 0x28, 0xe2, 0x26, 0x41, 0x13, 0x1a, 0x37, 0xb5, 0xe4, 0x93,
	0x50, 0xa0, 0xd8, 0x82, 0xcd, 0xb2, 0x08, 0x93, 0xa4, 0x03, 0xf5, 0x23, 0x4c, 0x72, 0x9f, 0x7d,
	0xa6, 0x1a, 0x62, 0x1d, 0xac, 0x0b, 0x8f, 0x52, 0x89, 0xa2, 0xe6, 0x34, 0x2b, 0xad, 0xaa, 0xaf,
	0x9e, 0xbd, 0x7d, 0xd8, 0x28, 0xe6, 0x18, 0xa4, 0xee, 0x0b, 0x58, 0x9c, 0x2a, 0xb4, 0xe6, 0x34,
	0x17, 0x5a, 0x55, 0x5f, 0xbf, 0x79, 0x0c, 0x1a, 0x67, 0x3c, 0x24, 0x09, 0x66, 0x87, 0xe9, 0xeb,
	0x71, 0xb6, 0xe4, 0x46, 0xb0, 0x4a, 0x59, 0x88, 0xb7, 0xb3, 0x3e, 0x89, 0x09, 0x57, 0x24, 0x4b,
	0x9d, 0x2d, 0x6b, 0x90, 0x4c, 0x86, 0x11, 0xe1, 0x2a, 0xdb, 0x7f, 0x4a, 0xed, 0xaf, 0x59, 0x03,
	0xca, 0x04, 0xcd, 0x06, 0x10, 0xf0, 0xba, 0x61, 0x38, 0x66, 0xbd, 0xcb, 0x54, 0x26, 0x28, 0xb2,
	0xc0, 0x21, 0xf9, 0x85, 0x76, 0x27, 0xdd, 0x4f, 0x00, 0xf4, 0x16, 0xd1, 0x86, 0xd6, 0x0b, 0x86,
	0x14, 0x9c, 0x5b, 0x31, 0xc2, 0xbd, 0xb7, 0xf0, 0xfa, 0x21, 0x09, 0xd3, 0xc9, 0x20, 0x9b, 0xb3,
	0x98, 0x5d, 0x61, 0x5f, 0xb0, 0x78, 0xbe, 0x9d, 0x46, 0xc1, 0x4e, 0xd5, 0x52, 0x54, 0x73, 0x38,
	0x87, 0xca, 0x94, 0xbd, 0xc8, 0x86, 0x84, 0x5f, 0x92, 0x40, 0xa3, 0x27, 0x34, 0x6f, 0x96, 0x21,
	0xf7, 0x15, 0x96, 0x33, 0xf2, 0x31, 0xb3, 0xea, 0x7f, 0x53, 0xa8, 0x7f, 0x10, 0xde, 0x84, 0x1c,
	0x93, 0x38, 0xa7, 0xf7, 0xad, 0x4c, 0xcf, 0x83, 0x66, 0xa9, 0x98, 0x69, 0x68, 0x13, 0x36, 0xee,
	0x0e, 0xad, 0xcc, 0xf1, 0x0e, 0xb4, 0x7a, 0x33, 0x0c, 0x2e, 0xfa, 0x4c, 0x98, 0xfb, 0x24, 0xa2,
	0xd3, 0xc2, 0x62, 0xf2, 0xae, 0x61, 0x7b, 0x7e, 0xac, 0x39, 0xb7, 0x43, 0x78, 0x16, 0x96, 0x04,
	0xe9, 0x7a, 0x6b, 0x25, 0xf5, 0xe6, 0x35, 0x96, 0x66, 0x79, 0x17, 0xf0, 0xf2, 0x81, 0xa6, 0xb8,
	0x7b, 0xb0, 0x48, 0x15, 0xa4, 0x96, 0xe4, 0x3c, 0x6a, 0x1d, 0x77, 0xef, 0xc4, 0x2b, 0x85, 0x13,
	0x3f, 0x84, 0xd5, 0x6e, 0x90, 0x44, 0x57, 0xe8, 0x8f, 0x06, 0xf4, 0x9c, 0xe5, 0x32, 0x75, 0xa8,
	0x06, 0xf9, 0xe1, 0x6b, 0xa5, 0xaa, 0x7f, 0xf7, 0x21, 0xfb, 0x6b, 0x8b, 0x78, 0x10, 0xd6, 0x2a,
	0x0a, 0x50, 0xcf, 0x3b, 0x9f, 0xe1, 0x79, 0xe9, 0x8a, 0x76, 0x01, 0xf4, 0x92, 0x5e, 0x71, 0xdc,
	0x65, 0x78, 0x7c, 0xe4, 0x77, 0x7b, 0x87, 0xfd, 0xb3, 0xe1, 0x4a, 0x25, 0x7b, 0xeb, 0x9f, 0xf8,
	0xf9, 0xdb, 0xc2, 0xc1, 0x10, 0xea, 0x4c, 0x4c, 0xdb, 0x84, 0x93, 0x60, 0x86, 0x56, 0x55, 0xea,
	0xfe, 0x39, 0x78, 0xf7, 0x93, 0x08, 0x7a, 0xaa, 0x2e, 0xb4, 0xbb, 0x3f, 0xaa, 0xba, 0xcf, 0xf4,
	0x8a, 0x52, 0x72, 0xf2, 0x8f, 0xe3, 0xfc, 0x75, 0x9c, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x45,
	0x09, 0xf3, 0x23, 0x07, 0x07, 0x00, 0x00,
}
