// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yarn_service_protos.proto

package hadoop_yarn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hadoop_common "github.com/stormgbs/go-hadoop/hadoop_common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SchedulerResourceTypes int32

const (
	SchedulerResourceTypes_MEMORY SchedulerResourceTypes = 0
	SchedulerResourceTypes_CPU    SchedulerResourceTypes = 1
)

var SchedulerResourceTypes_name = map[int32]string{
	0: "MEMORY",
	1: "CPU",
}
var SchedulerResourceTypes_value = map[string]int32{
	"MEMORY": 0,
	"CPU":    1,
}

func (x SchedulerResourceTypes) Enum() *SchedulerResourceTypes {
	p := new(SchedulerResourceTypes)
	*p = x
	return p
}
func (x SchedulerResourceTypes) String() string {
	return proto.EnumName(SchedulerResourceTypes_name, int32(x))
}
func (x *SchedulerResourceTypes) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SchedulerResourceTypes_value, data, "SchedulerResourceTypes")
	if err != nil {
		return err
	}
	*x = SchedulerResourceTypes(value)
	return nil
}
func (SchedulerResourceTypes) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type ApplicationsRequestScopeProto int32

const (
	ApplicationsRequestScopeProto_ALL      ApplicationsRequestScopeProto = 0
	ApplicationsRequestScopeProto_VIEWABLE ApplicationsRequestScopeProto = 1
	ApplicationsRequestScopeProto_OWN      ApplicationsRequestScopeProto = 2
)

var ApplicationsRequestScopeProto_name = map[int32]string{
	0: "ALL",
	1: "VIEWABLE",
	2: "OWN",
}
var ApplicationsRequestScopeProto_value = map[string]int32{
	"ALL":      0,
	"VIEWABLE": 1,
	"OWN":      2,
}

func (x ApplicationsRequestScopeProto) Enum() *ApplicationsRequestScopeProto {
	p := new(ApplicationsRequestScopeProto)
	*p = x
	return p
}
func (x ApplicationsRequestScopeProto) String() string {
	return proto.EnumName(ApplicationsRequestScopeProto_name, int32(x))
}
func (x *ApplicationsRequestScopeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApplicationsRequestScopeProto_value, data, "ApplicationsRequestScopeProto")
	if err != nil {
		return err
	}
	*x = ApplicationsRequestScopeProto(value)
	return nil
}
func (ApplicationsRequestScopeProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{1}
}

// ////////////////////////////////////////////////////
// ///// AM_RM_Protocol ///////////////////////////////
// ////////////////////////////////////////////////////
type RegisterApplicationMasterRequestProto struct {
	Host             *string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	RpcPort          *int32  `protobuf:"varint,2,opt,name=rpc_port,json=rpcPort" json:"rpc_port,omitempty"`
	TrackingUrl      *string `protobuf:"bytes,3,opt,name=tracking_url,json=trackingUrl" json:"tracking_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterApplicationMasterRequestProto) Reset()         { *m = RegisterApplicationMasterRequestProto{} }
func (m *RegisterApplicationMasterRequestProto) String() string { return proto.CompactTextString(m) }
func (*RegisterApplicationMasterRequestProto) ProtoMessage()    {}
func (*RegisterApplicationMasterRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0}
}

func (m *RegisterApplicationMasterRequestProto) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *RegisterApplicationMasterRequestProto) GetRpcPort() int32 {
	if m != nil && m.RpcPort != nil {
		return *m.RpcPort
	}
	return 0
}

func (m *RegisterApplicationMasterRequestProto) GetTrackingUrl() string {
	if m != nil && m.TrackingUrl != nil {
		return *m.TrackingUrl
	}
	return ""
}

type RegisterApplicationMasterResponseProto struct {
	MaximumCapability              *ResourceProto            `protobuf:"bytes,1,opt,name=maximumCapability" json:"maximumCapability,omitempty"`
	ClientToAmTokenMasterKey       []byte                    `protobuf:"bytes,2,opt,name=client_to_am_token_master_key,json=clientToAmTokenMasterKey" json:"client_to_am_token_master_key,omitempty"`
	Application_ACLs               []*ApplicationACLMapProto `protobuf:"bytes,3,rep,name=application_ACLs,json=applicationACLs" json:"application_ACLs,omitempty"`
	ContainersFromPreviousAttempts []*ContainerProto         `protobuf:"bytes,4,rep,name=containers_from_previous_attempts,json=containersFromPreviousAttempts" json:"containers_from_previous_attempts,omitempty"`
	Queue                          *string                   `protobuf:"bytes,5,opt,name=queue" json:"queue,omitempty"`
	NmTokensFromPreviousAttempts   []*NMTokenProto           `protobuf:"bytes,6,rep,name=nm_tokens_from_previous_attempts,json=nmTokensFromPreviousAttempts" json:"nm_tokens_from_previous_attempts,omitempty"`
	SchedulerResourceTypes         []SchedulerResourceTypes  `protobuf:"varint,7,rep,name=scheduler_resource_types,json=schedulerResourceTypes,enum=hadoop.yarn.SchedulerResourceTypes" json:"scheduler_resource_types,omitempty"`
	XXX_unrecognized               []byte                    `json:"-"`
}

func (m *RegisterApplicationMasterResponseProto) Reset() {
	*m = RegisterApplicationMasterResponseProto{}
}
func (m *RegisterApplicationMasterResponseProto) String() string { return proto.CompactTextString(m) }
func (*RegisterApplicationMasterResponseProto) ProtoMessage()    {}
func (*RegisterApplicationMasterResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{1}
}

func (m *RegisterApplicationMasterResponseProto) GetMaximumCapability() *ResourceProto {
	if m != nil {
		return m.MaximumCapability
	}
	return nil
}

func (m *RegisterApplicationMasterResponseProto) GetClientToAmTokenMasterKey() []byte {
	if m != nil {
		return m.ClientToAmTokenMasterKey
	}
	return nil
}

func (m *RegisterApplicationMasterResponseProto) GetApplication_ACLs() []*ApplicationACLMapProto {
	if m != nil {
		return m.Application_ACLs
	}
	return nil
}

func (m *RegisterApplicationMasterResponseProto) GetContainersFromPreviousAttempts() []*ContainerProto {
	if m != nil {
		return m.ContainersFromPreviousAttempts
	}
	return nil
}

func (m *RegisterApplicationMasterResponseProto) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

func (m *RegisterApplicationMasterResponseProto) GetNmTokensFromPreviousAttempts() []*NMTokenProto {
	if m != nil {
		return m.NmTokensFromPreviousAttempts
	}
	return nil
}

func (m *RegisterApplicationMasterResponseProto) GetSchedulerResourceTypes() []SchedulerResourceTypes {
	if m != nil {
		return m.SchedulerResourceTypes
	}
	return nil
}

type FinishApplicationMasterRequestProto struct {
	Diagnostics            *string                      `protobuf:"bytes,1,opt,name=diagnostics" json:"diagnostics,omitempty"`
	TrackingUrl            *string                      `protobuf:"bytes,2,opt,name=tracking_url,json=trackingUrl" json:"tracking_url,omitempty"`
	FinalApplicationStatus *FinalApplicationStatusProto `protobuf:"varint,3,opt,name=final_application_status,json=finalApplicationStatus,enum=hadoop.yarn.FinalApplicationStatusProto" json:"final_application_status,omitempty"`
	XXX_unrecognized       []byte                       `json:"-"`
}

func (m *FinishApplicationMasterRequestProto) Reset()         { *m = FinishApplicationMasterRequestProto{} }
func (m *FinishApplicationMasterRequestProto) String() string { return proto.CompactTextString(m) }
func (*FinishApplicationMasterRequestProto) ProtoMessage()    {}
func (*FinishApplicationMasterRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{2}
}

func (m *FinishApplicationMasterRequestProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return ""
}

func (m *FinishApplicationMasterRequestProto) GetTrackingUrl() string {
	if m != nil && m.TrackingUrl != nil {
		return *m.TrackingUrl
	}
	return ""
}

func (m *FinishApplicationMasterRequestProto) GetFinalApplicationStatus() FinalApplicationStatusProto {
	if m != nil && m.FinalApplicationStatus != nil {
		return *m.FinalApplicationStatus
	}
	return FinalApplicationStatusProto_APP_UNDEFINED
}

type FinishApplicationMasterResponseProto struct {
	IsUnregistered   *bool  `protobuf:"varint,1,opt,name=isUnregistered,def=0" json:"isUnregistered,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishApplicationMasterResponseProto) Reset()         { *m = FinishApplicationMasterResponseProto{} }
func (m *FinishApplicationMasterResponseProto) String() string { return proto.CompactTextString(m) }
func (*FinishApplicationMasterResponseProto) ProtoMessage()    {}
func (*FinishApplicationMasterResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{3}
}

const Default_FinishApplicationMasterResponseProto_IsUnregistered bool = false

func (m *FinishApplicationMasterResponseProto) GetIsUnregistered() bool {
	if m != nil && m.IsUnregistered != nil {
		return *m.IsUnregistered
	}
	return Default_FinishApplicationMasterResponseProto_IsUnregistered
}

type AllocateRequestProto struct {
	Ask              []*ResourceRequestProto                  `protobuf:"bytes,1,rep,name=ask" json:"ask,omitempty"`
	Release          []*ContainerIdProto                      `protobuf:"bytes,2,rep,name=release" json:"release,omitempty"`
	BlacklistRequest *ResourceBlacklistRequestProto           `protobuf:"bytes,3,opt,name=blacklist_request,json=blacklistRequest" json:"blacklist_request,omitempty"`
	ResponseId       *int32                                   `protobuf:"varint,4,opt,name=response_id,json=responseId" json:"response_id,omitempty"`
	Progress         *float32                                 `protobuf:"fixed32,5,opt,name=progress" json:"progress,omitempty"`
	IncreaseRequest  []*ContainerResourceIncreaseRequestProto `protobuf:"bytes,6,rep,name=increase_request,json=increaseRequest" json:"increase_request,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *AllocateRequestProto) Reset()                    { *m = AllocateRequestProto{} }
func (m *AllocateRequestProto) String() string            { return proto.CompactTextString(m) }
func (*AllocateRequestProto) ProtoMessage()               {}
func (*AllocateRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *AllocateRequestProto) GetAsk() []*ResourceRequestProto {
	if m != nil {
		return m.Ask
	}
	return nil
}

func (m *AllocateRequestProto) GetRelease() []*ContainerIdProto {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *AllocateRequestProto) GetBlacklistRequest() *ResourceBlacklistRequestProto {
	if m != nil {
		return m.BlacklistRequest
	}
	return nil
}

func (m *AllocateRequestProto) GetResponseId() int32 {
	if m != nil && m.ResponseId != nil {
		return *m.ResponseId
	}
	return 0
}

func (m *AllocateRequestProto) GetProgress() float32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

func (m *AllocateRequestProto) GetIncreaseRequest() []*ContainerResourceIncreaseRequestProto {
	if m != nil {
		return m.IncreaseRequest
	}
	return nil
}

type NMTokenProto struct {
	NodeId           *NodeIdProto              `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
	Token            *hadoop_common.TokenProto `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *NMTokenProto) Reset()                    { *m = NMTokenProto{} }
func (m *NMTokenProto) String() string            { return proto.CompactTextString(m) }
func (*NMTokenProto) ProtoMessage()               {}
func (*NMTokenProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *NMTokenProto) GetNodeId() *NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *NMTokenProto) GetToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.Token
	}
	return nil
}

type AllocateResponseProto struct {
	AMCommand                  *AMCommandProto                   `protobuf:"varint,1,opt,name=a_m_command,json=aMCommand,enum=hadoop.yarn.AMCommandProto" json:"a_m_command,omitempty"`
	ResponseId                 *int32                            `protobuf:"varint,2,opt,name=response_id,json=responseId" json:"response_id,omitempty"`
	AllocatedContainers        []*ContainerProto                 `protobuf:"bytes,3,rep,name=allocated_containers,json=allocatedContainers" json:"allocated_containers,omitempty"`
	CompletedContainerStatuses []*ContainerStatusProto           `protobuf:"bytes,4,rep,name=completed_container_statuses,json=completedContainerStatuses" json:"completed_container_statuses,omitempty"`
	Limit                      *ResourceProto                    `protobuf:"bytes,5,opt,name=limit" json:"limit,omitempty"`
	UpdatedNodes               []*NodeReportProto                `protobuf:"bytes,6,rep,name=updated_nodes,json=updatedNodes" json:"updated_nodes,omitempty"`
	NumClusterNodes            *int32                            `protobuf:"varint,7,opt,name=num_cluster_nodes,json=numClusterNodes" json:"num_cluster_nodes,omitempty"`
	Preempt                    *PreemptionMessageProto           `protobuf:"bytes,8,opt,name=preempt" json:"preempt,omitempty"`
	NmTokens                   []*NMTokenProto                   `protobuf:"bytes,9,rep,name=nm_tokens,json=nmTokens" json:"nm_tokens,omitempty"`
	IncreasedContainers        []*ContainerResourceIncreaseProto `protobuf:"bytes,10,rep,name=increased_containers,json=increasedContainers" json:"increased_containers,omitempty"`
	DecreasedContainers        []*ContainerResourceDecreaseProto `protobuf:"bytes,11,rep,name=decreased_containers,json=decreasedContainers" json:"decreased_containers,omitempty"`
	AmRmToken                  *hadoop_common.TokenProto         `protobuf:"bytes,12,opt,name=am_rm_token,json=amRmToken" json:"am_rm_token,omitempty"`
	XXX_unrecognized           []byte                            `json:"-"`
}

func (m *AllocateResponseProto) Reset()                    { *m = AllocateResponseProto{} }
func (m *AllocateResponseProto) String() string            { return proto.CompactTextString(m) }
func (*AllocateResponseProto) ProtoMessage()               {}
func (*AllocateResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *AllocateResponseProto) GetAMCommand() AMCommandProto {
	if m != nil && m.AMCommand != nil {
		return *m.AMCommand
	}
	return AMCommandProto_AM_RESYNC
}

func (m *AllocateResponseProto) GetResponseId() int32 {
	if m != nil && m.ResponseId != nil {
		return *m.ResponseId
	}
	return 0
}

func (m *AllocateResponseProto) GetAllocatedContainers() []*ContainerProto {
	if m != nil {
		return m.AllocatedContainers
	}
	return nil
}

func (m *AllocateResponseProto) GetCompletedContainerStatuses() []*ContainerStatusProto {
	if m != nil {
		return m.CompletedContainerStatuses
	}
	return nil
}

func (m *AllocateResponseProto) GetLimit() *ResourceProto {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *AllocateResponseProto) GetUpdatedNodes() []*NodeReportProto {
	if m != nil {
		return m.UpdatedNodes
	}
	return nil
}

func (m *AllocateResponseProto) GetNumClusterNodes() int32 {
	if m != nil && m.NumClusterNodes != nil {
		return *m.NumClusterNodes
	}
	return 0
}

func (m *AllocateResponseProto) GetPreempt() *PreemptionMessageProto {
	if m != nil {
		return m.Preempt
	}
	return nil
}

func (m *AllocateResponseProto) GetNmTokens() []*NMTokenProto {
	if m != nil {
		return m.NmTokens
	}
	return nil
}

func (m *AllocateResponseProto) GetIncreasedContainers() []*ContainerResourceIncreaseProto {
	if m != nil {
		return m.IncreasedContainers
	}
	return nil
}

func (m *AllocateResponseProto) GetDecreasedContainers() []*ContainerResourceDecreaseProto {
	if m != nil {
		return m.DecreasedContainers
	}
	return nil
}

func (m *AllocateResponseProto) GetAmRmToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.AmRmToken
	}
	return nil
}

type GetNewApplicationRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetNewApplicationRequestProto) Reset()                    { *m = GetNewApplicationRequestProto{} }
func (m *GetNewApplicationRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetNewApplicationRequestProto) ProtoMessage()               {}
func (*GetNewApplicationRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

type GetNewApplicationResponseProto struct {
	ApplicationId     *ApplicationIdProto `protobuf:"bytes,1,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
	MaximumCapability *ResourceProto      `protobuf:"bytes,2,opt,name=maximumCapability" json:"maximumCapability,omitempty"`
	XXX_unrecognized  []byte              `json:"-"`
}

func (m *GetNewApplicationResponseProto) Reset()                    { *m = GetNewApplicationResponseProto{} }
func (m *GetNewApplicationResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetNewApplicationResponseProto) ProtoMessage()               {}
func (*GetNewApplicationResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *GetNewApplicationResponseProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *GetNewApplicationResponseProto) GetMaximumCapability() *ResourceProto {
	if m != nil {
		return m.MaximumCapability
	}
	return nil
}

type GetApplicationReportRequestProto struct {
	ApplicationId    *ApplicationIdProto `protobuf:"bytes,1,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetApplicationReportRequestProto) Reset()         { *m = GetApplicationReportRequestProto{} }
func (m *GetApplicationReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetApplicationReportRequestProto) ProtoMessage()    {}
func (*GetApplicationReportRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{9}
}

func (m *GetApplicationReportRequestProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

type GetApplicationReportResponseProto struct {
	ApplicationReport *ApplicationReportProto `protobuf:"bytes,1,opt,name=application_report,json=applicationReport" json:"application_report,omitempty"`
	XXX_unrecognized  []byte                  `json:"-"`
}

func (m *GetApplicationReportResponseProto) Reset()         { *m = GetApplicationReportResponseProto{} }
func (m *GetApplicationReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetApplicationReportResponseProto) ProtoMessage()    {}
func (*GetApplicationReportResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{10}
}

func (m *GetApplicationReportResponseProto) GetApplicationReport() *ApplicationReportProto {
	if m != nil {
		return m.ApplicationReport
	}
	return nil
}

type SubmitApplicationRequestProto struct {
	ApplicationSubmissionContext *ApplicationSubmissionContextProto `protobuf:"bytes,1,opt,name=application_submission_context,json=applicationSubmissionContext" json:"application_submission_context,omitempty"`
	XXX_unrecognized             []byte                             `json:"-"`
}

func (m *SubmitApplicationRequestProto) Reset()                    { *m = SubmitApplicationRequestProto{} }
func (m *SubmitApplicationRequestProto) String() string            { return proto.CompactTextString(m) }
func (*SubmitApplicationRequestProto) ProtoMessage()               {}
func (*SubmitApplicationRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *SubmitApplicationRequestProto) GetApplicationSubmissionContext() *ApplicationSubmissionContextProto {
	if m != nil {
		return m.ApplicationSubmissionContext
	}
	return nil
}

type SubmitApplicationResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SubmitApplicationResponseProto) Reset()                    { *m = SubmitApplicationResponseProto{} }
func (m *SubmitApplicationResponseProto) String() string            { return proto.CompactTextString(m) }
func (*SubmitApplicationResponseProto) ProtoMessage()               {}
func (*SubmitApplicationResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

type KillApplicationRequestProto struct {
	ApplicationId    *ApplicationIdProto `protobuf:"bytes,1,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *KillApplicationRequestProto) Reset()                    { *m = KillApplicationRequestProto{} }
func (m *KillApplicationRequestProto) String() string            { return proto.CompactTextString(m) }
func (*KillApplicationRequestProto) ProtoMessage()               {}
func (*KillApplicationRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{13} }

func (m *KillApplicationRequestProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

type KillApplicationResponseProto struct {
	IsKillCompleted  *bool  `protobuf:"varint,1,opt,name=is_kill_completed,json=isKillCompleted,def=0" json:"is_kill_completed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KillApplicationResponseProto) Reset()                    { *m = KillApplicationResponseProto{} }
func (m *KillApplicationResponseProto) String() string            { return proto.CompactTextString(m) }
func (*KillApplicationResponseProto) ProtoMessage()               {}
func (*KillApplicationResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{14} }

const Default_KillApplicationResponseProto_IsKillCompleted bool = false

func (m *KillApplicationResponseProto) GetIsKillCompleted() bool {
	if m != nil && m.IsKillCompleted != nil {
		return *m.IsKillCompleted
	}
	return Default_KillApplicationResponseProto_IsKillCompleted
}

type GetClusterMetricsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetClusterMetricsRequestProto) Reset()                    { *m = GetClusterMetricsRequestProto{} }
func (m *GetClusterMetricsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetClusterMetricsRequestProto) ProtoMessage()               {}
func (*GetClusterMetricsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{15} }

type GetClusterMetricsResponseProto struct {
	ClusterMetrics   *YarnClusterMetricsProto `protobuf:"bytes,1,opt,name=cluster_metrics,json=clusterMetrics" json:"cluster_metrics,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *GetClusterMetricsResponseProto) Reset()                    { *m = GetClusterMetricsResponseProto{} }
func (m *GetClusterMetricsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetClusterMetricsResponseProto) ProtoMessage()               {}
func (*GetClusterMetricsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{16} }

func (m *GetClusterMetricsResponseProto) GetClusterMetrics() *YarnClusterMetricsProto {
	if m != nil {
		return m.ClusterMetrics
	}
	return nil
}

type MoveApplicationAcrossQueuesRequestProto struct {
	ApplicationId    *ApplicationIdProto `protobuf:"bytes,1,req,name=application_id,json=applicationId" json:"application_id,omitempty"`
	TargetQueue      *string             `protobuf:"bytes,2,req,name=target_queue,json=targetQueue" json:"target_queue,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MoveApplicationAcrossQueuesRequestProto) Reset() {
	*m = MoveApplicationAcrossQueuesRequestProto{}
}
func (m *MoveApplicationAcrossQueuesRequestProto) String() string { return proto.CompactTextString(m) }
func (*MoveApplicationAcrossQueuesRequestProto) ProtoMessage()    {}
func (*MoveApplicationAcrossQueuesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{17}
}

func (m *MoveApplicationAcrossQueuesRequestProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *MoveApplicationAcrossQueuesRequestProto) GetTargetQueue() string {
	if m != nil && m.TargetQueue != nil {
		return *m.TargetQueue
	}
	return ""
}

type MoveApplicationAcrossQueuesResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MoveApplicationAcrossQueuesResponseProto) Reset() {
	*m = MoveApplicationAcrossQueuesResponseProto{}
}
func (m *MoveApplicationAcrossQueuesResponseProto) String() string { return proto.CompactTextString(m) }
func (*MoveApplicationAcrossQueuesResponseProto) ProtoMessage()    {}
func (*MoveApplicationAcrossQueuesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{18}
}

type GetApplicationsRequestProto struct {
	ApplicationTypes  []string                       `protobuf:"bytes,1,rep,name=application_types,json=applicationTypes" json:"application_types,omitempty"`
	ApplicationStates []YarnApplicationStateProto    `protobuf:"varint,2,rep,name=application_states,json=applicationStates,enum=hadoop.yarn.YarnApplicationStateProto" json:"application_states,omitempty"`
	Users             []string                       `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	Queues            []string                       `protobuf:"bytes,4,rep,name=queues" json:"queues,omitempty"`
	Limit             *int64                         `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	StartBegin        *int64                         `protobuf:"varint,6,opt,name=start_begin,json=startBegin" json:"start_begin,omitempty"`
	StartEnd          *int64                         `protobuf:"varint,7,opt,name=start_end,json=startEnd" json:"start_end,omitempty"`
	FinishBegin       *int64                         `protobuf:"varint,8,opt,name=finish_begin,json=finishBegin" json:"finish_begin,omitempty"`
	FinishEnd         *int64                         `protobuf:"varint,9,opt,name=finish_end,json=finishEnd" json:"finish_end,omitempty"`
	ApplicationTags   []string                       `protobuf:"bytes,10,rep,name=applicationTags" json:"applicationTags,omitempty"`
	Scope             *ApplicationsRequestScopeProto `protobuf:"varint,11,opt,name=scope,enum=hadoop.yarn.ApplicationsRequestScopeProto,def=0" json:"scope,omitempty"`
	XXX_unrecognized  []byte                         `json:"-"`
}

func (m *GetApplicationsRequestProto) Reset()                    { *m = GetApplicationsRequestProto{} }
func (m *GetApplicationsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationsRequestProto) ProtoMessage()               {}
func (*GetApplicationsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{19} }

const Default_GetApplicationsRequestProto_Scope ApplicationsRequestScopeProto = ApplicationsRequestScopeProto_ALL

func (m *GetApplicationsRequestProto) GetApplicationTypes() []string {
	if m != nil {
		return m.ApplicationTypes
	}
	return nil
}

func (m *GetApplicationsRequestProto) GetApplicationStates() []YarnApplicationStateProto {
	if m != nil {
		return m.ApplicationStates
	}
	return nil
}

func (m *GetApplicationsRequestProto) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetApplicationsRequestProto) GetQueues() []string {
	if m != nil {
		return m.Queues
	}
	return nil
}

func (m *GetApplicationsRequestProto) GetLimit() int64 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *GetApplicationsRequestProto) GetStartBegin() int64 {
	if m != nil && m.StartBegin != nil {
		return *m.StartBegin
	}
	return 0
}

func (m *GetApplicationsRequestProto) GetStartEnd() int64 {
	if m != nil && m.StartEnd != nil {
		return *m.StartEnd
	}
	return 0
}

func (m *GetApplicationsRequestProto) GetFinishBegin() int64 {
	if m != nil && m.FinishBegin != nil {
		return *m.FinishBegin
	}
	return 0
}

func (m *GetApplicationsRequestProto) GetFinishEnd() int64 {
	if m != nil && m.FinishEnd != nil {
		return *m.FinishEnd
	}
	return 0
}

func (m *GetApplicationsRequestProto) GetApplicationTags() []string {
	if m != nil {
		return m.ApplicationTags
	}
	return nil
}

func (m *GetApplicationsRequestProto) GetScope() ApplicationsRequestScopeProto {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return Default_GetApplicationsRequestProto_Scope
}

type GetApplicationsResponseProto struct {
	Applications     []*ApplicationReportProto `protobuf:"bytes,1,rep,name=applications" json:"applications,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *GetApplicationsResponseProto) Reset()                    { *m = GetApplicationsResponseProto{} }
func (m *GetApplicationsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationsResponseProto) ProtoMessage()               {}
func (*GetApplicationsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{20} }

func (m *GetApplicationsResponseProto) GetApplications() []*ApplicationReportProto {
	if m != nil {
		return m.Applications
	}
	return nil
}

type GetClusterNodesRequestProto struct {
	NodeStates       []NodeStateProto `protobuf:"varint,1,rep,name=nodeStates,enum=hadoop.yarn.NodeStateProto" json:"nodeStates,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetClusterNodesRequestProto) Reset()                    { *m = GetClusterNodesRequestProto{} }
func (m *GetClusterNodesRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetClusterNodesRequestProto) ProtoMessage()               {}
func (*GetClusterNodesRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{21} }

func (m *GetClusterNodesRequestProto) GetNodeStates() []NodeStateProto {
	if m != nil {
		return m.NodeStates
	}
	return nil
}

type GetClusterNodesResponseProto struct {
	NodeReports      []*NodeReportProto `protobuf:"bytes,1,rep,name=nodeReports" json:"nodeReports,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetClusterNodesResponseProto) Reset()                    { *m = GetClusterNodesResponseProto{} }
func (m *GetClusterNodesResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetClusterNodesResponseProto) ProtoMessage()               {}
func (*GetClusterNodesResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{22} }

func (m *GetClusterNodesResponseProto) GetNodeReports() []*NodeReportProto {
	if m != nil {
		return m.NodeReports
	}
	return nil
}

type GetQueueInfoRequestProto struct {
	QueueName           *string `protobuf:"bytes,1,opt,name=queueName" json:"queueName,omitempty"`
	IncludeApplications *bool   `protobuf:"varint,2,opt,name=includeApplications" json:"includeApplications,omitempty"`
	IncludeChildQueues  *bool   `protobuf:"varint,3,opt,name=includeChildQueues" json:"includeChildQueues,omitempty"`
	Recursive           *bool   `protobuf:"varint,4,opt,name=recursive" json:"recursive,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *GetQueueInfoRequestProto) Reset()                    { *m = GetQueueInfoRequestProto{} }
func (m *GetQueueInfoRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetQueueInfoRequestProto) ProtoMessage()               {}
func (*GetQueueInfoRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{23} }

func (m *GetQueueInfoRequestProto) GetQueueName() string {
	if m != nil && m.QueueName != nil {
		return *m.QueueName
	}
	return ""
}

func (m *GetQueueInfoRequestProto) GetIncludeApplications() bool {
	if m != nil && m.IncludeApplications != nil {
		return *m.IncludeApplications
	}
	return false
}

func (m *GetQueueInfoRequestProto) GetIncludeChildQueues() bool {
	if m != nil && m.IncludeChildQueues != nil {
		return *m.IncludeChildQueues
	}
	return false
}

func (m *GetQueueInfoRequestProto) GetRecursive() bool {
	if m != nil && m.Recursive != nil {
		return *m.Recursive
	}
	return false
}

type GetQueueInfoResponseProto struct {
	QueueInfo        *QueueInfoProto `protobuf:"bytes,1,opt,name=queueInfo" json:"queueInfo,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetQueueInfoResponseProto) Reset()                    { *m = GetQueueInfoResponseProto{} }
func (m *GetQueueInfoResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetQueueInfoResponseProto) ProtoMessage()               {}
func (*GetQueueInfoResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{24} }

func (m *GetQueueInfoResponseProto) GetQueueInfo() *QueueInfoProto {
	if m != nil {
		return m.QueueInfo
	}
	return nil
}

type GetQueueUserAclsInfoRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetQueueUserAclsInfoRequestProto) Reset()         { *m = GetQueueUserAclsInfoRequestProto{} }
func (m *GetQueueUserAclsInfoRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetQueueUserAclsInfoRequestProto) ProtoMessage()    {}
func (*GetQueueUserAclsInfoRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{25}
}

type GetQueueUserAclsInfoResponseProto struct {
	QueueUserAcls    []*QueueUserACLInfoProto `protobuf:"bytes,1,rep,name=queueUserAcls" json:"queueUserAcls,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *GetQueueUserAclsInfoResponseProto) Reset()         { *m = GetQueueUserAclsInfoResponseProto{} }
func (m *GetQueueUserAclsInfoResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetQueueUserAclsInfoResponseProto) ProtoMessage()    {}
func (*GetQueueUserAclsInfoResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{26}
}

func (m *GetQueueUserAclsInfoResponseProto) GetQueueUserAcls() []*QueueUserACLInfoProto {
	if m != nil {
		return m.QueueUserAcls
	}
	return nil
}

type GetNodesToLabelsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetNodesToLabelsRequestProto) Reset()                    { *m = GetNodesToLabelsRequestProto{} }
func (m *GetNodesToLabelsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetNodesToLabelsRequestProto) ProtoMessage()               {}
func (*GetNodesToLabelsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{27} }

type GetNodesToLabelsResponseProto struct {
	NodeToLabels     []*NodeIdToLabelsInfoProto `protobuf:"bytes,1,rep,name=nodeToLabels" json:"nodeToLabels,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *GetNodesToLabelsResponseProto) Reset()                    { *m = GetNodesToLabelsResponseProto{} }
func (m *GetNodesToLabelsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetNodesToLabelsResponseProto) ProtoMessage()               {}
func (*GetNodesToLabelsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{28} }

func (m *GetNodesToLabelsResponseProto) GetNodeToLabels() []*NodeIdToLabelsInfoProto {
	if m != nil {
		return m.NodeToLabels
	}
	return nil
}

type GetLabelsToNodesRequestProto struct {
	NodeLabels       []string `protobuf:"bytes,1,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetLabelsToNodesRequestProto) Reset()                    { *m = GetLabelsToNodesRequestProto{} }
func (m *GetLabelsToNodesRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetLabelsToNodesRequestProto) ProtoMessage()               {}
func (*GetLabelsToNodesRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{29} }

func (m *GetLabelsToNodesRequestProto) GetNodeLabels() []string {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

type GetLabelsToNodesResponseProto struct {
	LabelsToNodes    []*LabelsToNodeIdsProto `protobuf:"bytes,1,rep,name=labelsToNodes" json:"labelsToNodes,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetLabelsToNodesResponseProto) Reset()                    { *m = GetLabelsToNodesResponseProto{} }
func (m *GetLabelsToNodesResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetLabelsToNodesResponseProto) ProtoMessage()               {}
func (*GetLabelsToNodesResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{30} }

func (m *GetLabelsToNodesResponseProto) GetLabelsToNodes() []*LabelsToNodeIdsProto {
	if m != nil {
		return m.LabelsToNodes
	}
	return nil
}

type GetClusterNodeLabelsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetClusterNodeLabelsRequestProto) Reset()         { *m = GetClusterNodeLabelsRequestProto{} }
func (m *GetClusterNodeLabelsRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetClusterNodeLabelsRequestProto) ProtoMessage()    {}
func (*GetClusterNodeLabelsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{31}
}

type GetClusterNodeLabelsResponseProto struct {
	NodeLabels       []*NodeLabelProto `protobuf:"bytes,1,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetClusterNodeLabelsResponseProto) Reset()         { *m = GetClusterNodeLabelsResponseProto{} }
func (m *GetClusterNodeLabelsResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetClusterNodeLabelsResponseProto) ProtoMessage()    {}
func (*GetClusterNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{32}
}

func (m *GetClusterNodeLabelsResponseProto) GetNodeLabels() []*NodeLabelProto {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

type StartContainerRequestProto struct {
	ContainerLaunchContext *ContainerLaunchContextProto `protobuf:"bytes,1,opt,name=container_launch_context,json=containerLaunchContext" json:"container_launch_context,omitempty"`
	ContainerToken         *hadoop_common.TokenProto    `protobuf:"bytes,2,opt,name=container_token,json=containerToken" json:"container_token,omitempty"`
	XXX_unrecognized       []byte                       `json:"-"`
}

func (m *StartContainerRequestProto) Reset()                    { *m = StartContainerRequestProto{} }
func (m *StartContainerRequestProto) String() string            { return proto.CompactTextString(m) }
func (*StartContainerRequestProto) ProtoMessage()               {}
func (*StartContainerRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{33} }

func (m *StartContainerRequestProto) GetContainerLaunchContext() *ContainerLaunchContextProto {
	if m != nil {
		return m.ContainerLaunchContext
	}
	return nil
}

func (m *StartContainerRequestProto) GetContainerToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.ContainerToken
	}
	return nil
}

type StartContainerResponseProto struct {
	ServicesMetaData []*StringBytesMapProto `protobuf:"bytes,1,rep,name=services_meta_data,json=servicesMetaData" json:"services_meta_data,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *StartContainerResponseProto) Reset()                    { *m = StartContainerResponseProto{} }
func (m *StartContainerResponseProto) String() string            { return proto.CompactTextString(m) }
func (*StartContainerResponseProto) ProtoMessage()               {}
func (*StartContainerResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{34} }

func (m *StartContainerResponseProto) GetServicesMetaData() []*StringBytesMapProto {
	if m != nil {
		return m.ServicesMetaData
	}
	return nil
}

type StopContainerRequestProto struct {
	ContainerId      *ContainerIdProto `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *StopContainerRequestProto) Reset()                    { *m = StopContainerRequestProto{} }
func (m *StopContainerRequestProto) String() string            { return proto.CompactTextString(m) }
func (*StopContainerRequestProto) ProtoMessage()               {}
func (*StopContainerRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{35} }

func (m *StopContainerRequestProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

type StopContainerResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StopContainerResponseProto) Reset()                    { *m = StopContainerResponseProto{} }
func (m *StopContainerResponseProto) String() string            { return proto.CompactTextString(m) }
func (*StopContainerResponseProto) ProtoMessage()               {}
func (*StopContainerResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{36} }

type GetContainerStatusRequestProto struct {
	ContainerId      *ContainerIdProto `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetContainerStatusRequestProto) Reset()                    { *m = GetContainerStatusRequestProto{} }
func (m *GetContainerStatusRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetContainerStatusRequestProto) ProtoMessage()               {}
func (*GetContainerStatusRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{37} }

func (m *GetContainerStatusRequestProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

type GetContainerStatusResponseProto struct {
	Status           *ContainerStatusProto `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GetContainerStatusResponseProto) Reset()         { *m = GetContainerStatusResponseProto{} }
func (m *GetContainerStatusResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetContainerStatusResponseProto) ProtoMessage()    {}
func (*GetContainerStatusResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{38}
}

func (m *GetContainerStatusResponseProto) GetStatus() *ContainerStatusProto {
	if m != nil {
		return m.Status
	}
	return nil
}

// // bulk API records
type StartContainersRequestProto struct {
	StartContainerRequest []*StartContainerRequestProto `protobuf:"bytes,1,rep,name=start_container_request,json=startContainerRequest" json:"start_container_request,omitempty"`
	XXX_unrecognized      []byte                        `json:"-"`
}

func (m *StartContainersRequestProto) Reset()                    { *m = StartContainersRequestProto{} }
func (m *StartContainersRequestProto) String() string            { return proto.CompactTextString(m) }
func (*StartContainersRequestProto) ProtoMessage()               {}
func (*StartContainersRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{39} }

func (m *StartContainersRequestProto) GetStartContainerRequest() []*StartContainerRequestProto {
	if m != nil {
		return m.StartContainerRequest
	}
	return nil
}

type ContainerExceptionMapProto struct {
	ContainerId      *ContainerIdProto         `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	Exception        *SerializedExceptionProto `protobuf:"bytes,2,opt,name=exception" json:"exception,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ContainerExceptionMapProto) Reset()                    { *m = ContainerExceptionMapProto{} }
func (m *ContainerExceptionMapProto) String() string            { return proto.CompactTextString(m) }
func (*ContainerExceptionMapProto) ProtoMessage()               {}
func (*ContainerExceptionMapProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{40} }

func (m *ContainerExceptionMapProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *ContainerExceptionMapProto) GetException() *SerializedExceptionProto {
	if m != nil {
		return m.Exception
	}
	return nil
}

type StartContainersResponseProto struct {
	ServicesMetaData  []*StringBytesMapProto        `protobuf:"bytes,1,rep,name=services_meta_data,json=servicesMetaData" json:"services_meta_data,omitempty"`
	SucceededRequests []*ContainerIdProto           `protobuf:"bytes,2,rep,name=succeeded_requests,json=succeededRequests" json:"succeeded_requests,omitempty"`
	FailedRequests    []*ContainerExceptionMapProto `protobuf:"bytes,3,rep,name=failed_requests,json=failedRequests" json:"failed_requests,omitempty"`
	XXX_unrecognized  []byte                        `json:"-"`
}

func (m *StartContainersResponseProto) Reset()                    { *m = StartContainersResponseProto{} }
func (m *StartContainersResponseProto) String() string            { return proto.CompactTextString(m) }
func (*StartContainersResponseProto) ProtoMessage()               {}
func (*StartContainersResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{41} }

func (m *StartContainersResponseProto) GetServicesMetaData() []*StringBytesMapProto {
	if m != nil {
		return m.ServicesMetaData
	}
	return nil
}

func (m *StartContainersResponseProto) GetSucceededRequests() []*ContainerIdProto {
	if m != nil {
		return m.SucceededRequests
	}
	return nil
}

func (m *StartContainersResponseProto) GetFailedRequests() []*ContainerExceptionMapProto {
	if m != nil {
		return m.FailedRequests
	}
	return nil
}

type StopContainersRequestProto struct {
	ContainerId      []*ContainerIdProto `protobuf:"bytes,1,rep,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *StopContainersRequestProto) Reset()                    { *m = StopContainersRequestProto{} }
func (m *StopContainersRequestProto) String() string            { return proto.CompactTextString(m) }
func (*StopContainersRequestProto) ProtoMessage()               {}
func (*StopContainersRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{42} }

func (m *StopContainersRequestProto) GetContainerId() []*ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

type StopContainersResponseProto struct {
	SucceededRequests []*ContainerIdProto           `protobuf:"bytes,1,rep,name=succeeded_requests,json=succeededRequests" json:"succeeded_requests,omitempty"`
	FailedRequests    []*ContainerExceptionMapProto `protobuf:"bytes,2,rep,name=failed_requests,json=failedRequests" json:"failed_requests,omitempty"`
	XXX_unrecognized  []byte                        `json:"-"`
}

func (m *StopContainersResponseProto) Reset()                    { *m = StopContainersResponseProto{} }
func (m *StopContainersResponseProto) String() string            { return proto.CompactTextString(m) }
func (*StopContainersResponseProto) ProtoMessage()               {}
func (*StopContainersResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{43} }

func (m *StopContainersResponseProto) GetSucceededRequests() []*ContainerIdProto {
	if m != nil {
		return m.SucceededRequests
	}
	return nil
}

func (m *StopContainersResponseProto) GetFailedRequests() []*ContainerExceptionMapProto {
	if m != nil {
		return m.FailedRequests
	}
	return nil
}

type GetContainerStatusesRequestProto struct {
	ContainerId      []*ContainerIdProto `protobuf:"bytes,1,rep,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetContainerStatusesRequestProto) Reset()         { *m = GetContainerStatusesRequestProto{} }
func (m *GetContainerStatusesRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetContainerStatusesRequestProto) ProtoMessage()    {}
func (*GetContainerStatusesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{44}
}

func (m *GetContainerStatusesRequestProto) GetContainerId() []*ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

type GetContainerStatusesResponseProto struct {
	Status           []*ContainerStatusProto       `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
	FailedRequests   []*ContainerExceptionMapProto `protobuf:"bytes,2,rep,name=failed_requests,json=failedRequests" json:"failed_requests,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *GetContainerStatusesResponseProto) Reset()         { *m = GetContainerStatusesResponseProto{} }
func (m *GetContainerStatusesResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetContainerStatusesResponseProto) ProtoMessage()    {}
func (*GetContainerStatusesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{45}
}

func (m *GetContainerStatusesResponseProto) GetStatus() []*ContainerStatusProto {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetContainerStatusesResponseProto) GetFailedRequests() []*ContainerExceptionMapProto {
	if m != nil {
		return m.FailedRequests
	}
	return nil
}

type GetApplicationAttemptReportRequestProto struct {
	ApplicationAttemptId *ApplicationAttemptIdProto `protobuf:"bytes,1,opt,name=application_attempt_id,json=applicationAttemptId" json:"application_attempt_id,omitempty"`
	XXX_unrecognized     []byte                     `json:"-"`
}

func (m *GetApplicationAttemptReportRequestProto) Reset() {
	*m = GetApplicationAttemptReportRequestProto{}
}
func (m *GetApplicationAttemptReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetApplicationAttemptReportRequestProto) ProtoMessage()    {}
func (*GetApplicationAttemptReportRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{46}
}

func (m *GetApplicationAttemptReportRequestProto) GetApplicationAttemptId() *ApplicationAttemptIdProto {
	if m != nil {
		return m.ApplicationAttemptId
	}
	return nil
}

type GetApplicationAttemptReportResponseProto struct {
	ApplicationAttemptReport *ApplicationAttemptReportProto `protobuf:"bytes,1,opt,name=application_attempt_report,json=applicationAttemptReport" json:"application_attempt_report,omitempty"`
	XXX_unrecognized         []byte                         `json:"-"`
}

func (m *GetApplicationAttemptReportResponseProto) Reset() {
	*m = GetApplicationAttemptReportResponseProto{}
}
func (m *GetApplicationAttemptReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetApplicationAttemptReportResponseProto) ProtoMessage()    {}
func (*GetApplicationAttemptReportResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{47}
}

func (m *GetApplicationAttemptReportResponseProto) GetApplicationAttemptReport() *ApplicationAttemptReportProto {
	if m != nil {
		return m.ApplicationAttemptReport
	}
	return nil
}

type GetApplicationAttemptsRequestProto struct {
	ApplicationId    *ApplicationIdProto `protobuf:"bytes,1,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetApplicationAttemptsRequestProto) Reset()         { *m = GetApplicationAttemptsRequestProto{} }
func (m *GetApplicationAttemptsRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetApplicationAttemptsRequestProto) ProtoMessage()    {}
func (*GetApplicationAttemptsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{48}
}

func (m *GetApplicationAttemptsRequestProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

type GetApplicationAttemptsResponseProto struct {
	ApplicationAttempts []*ApplicationAttemptReportProto `protobuf:"bytes,1,rep,name=application_attempts,json=applicationAttempts" json:"application_attempts,omitempty"`
	XXX_unrecognized    []byte                           `json:"-"`
}

func (m *GetApplicationAttemptsResponseProto) Reset()         { *m = GetApplicationAttemptsResponseProto{} }
func (m *GetApplicationAttemptsResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetApplicationAttemptsResponseProto) ProtoMessage()    {}
func (*GetApplicationAttemptsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{49}
}

func (m *GetApplicationAttemptsResponseProto) GetApplicationAttempts() []*ApplicationAttemptReportProto {
	if m != nil {
		return m.ApplicationAttempts
	}
	return nil
}

type GetContainerReportRequestProto struct {
	ContainerId      *ContainerIdProto `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetContainerReportRequestProto) Reset()                    { *m = GetContainerReportRequestProto{} }
func (m *GetContainerReportRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetContainerReportRequestProto) ProtoMessage()               {}
func (*GetContainerReportRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{50} }

func (m *GetContainerReportRequestProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

type GetContainerReportResponseProto struct {
	ContainerReport  *ContainerReportProto `protobuf:"bytes,1,opt,name=container_report,json=containerReport" json:"container_report,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GetContainerReportResponseProto) Reset()         { *m = GetContainerReportResponseProto{} }
func (m *GetContainerReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetContainerReportResponseProto) ProtoMessage()    {}
func (*GetContainerReportResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{51}
}

func (m *GetContainerReportResponseProto) GetContainerReport() *ContainerReportProto {
	if m != nil {
		return m.ContainerReport
	}
	return nil
}

type GetContainersRequestProto struct {
	ApplicationAttemptId *ApplicationAttemptIdProto `protobuf:"bytes,1,opt,name=application_attempt_id,json=applicationAttemptId" json:"application_attempt_id,omitempty"`
	XXX_unrecognized     []byte                     `json:"-"`
}

func (m *GetContainersRequestProto) Reset()                    { *m = GetContainersRequestProto{} }
func (m *GetContainersRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetContainersRequestProto) ProtoMessage()               {}
func (*GetContainersRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{52} }

func (m *GetContainersRequestProto) GetApplicationAttemptId() *ApplicationAttemptIdProto {
	if m != nil {
		return m.ApplicationAttemptId
	}
	return nil
}

type GetContainersResponseProto struct {
	Containers       []*ContainerReportProto `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetContainersResponseProto) Reset()                    { *m = GetContainersResponseProto{} }
func (m *GetContainersResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetContainersResponseProto) ProtoMessage()               {}
func (*GetContainersResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{53} }

func (m *GetContainersResponseProto) GetContainers() []*ContainerReportProto {
	if m != nil {
		return m.Containers
	}
	return nil
}

type UseSharedCacheResourceRequestProto struct {
	ApplicationId    *ApplicationIdProto `protobuf:"bytes,1,opt,name=applicationId" json:"applicationId,omitempty"`
	ResourceKey      *string             `protobuf:"bytes,2,opt,name=resourceKey" json:"resourceKey,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UseSharedCacheResourceRequestProto) Reset()         { *m = UseSharedCacheResourceRequestProto{} }
func (m *UseSharedCacheResourceRequestProto) String() string { return proto.CompactTextString(m) }
func (*UseSharedCacheResourceRequestProto) ProtoMessage()    {}
func (*UseSharedCacheResourceRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{54}
}

func (m *UseSharedCacheResourceRequestProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *UseSharedCacheResourceRequestProto) GetResourceKey() string {
	if m != nil && m.ResourceKey != nil {
		return *m.ResourceKey
	}
	return ""
}

type UseSharedCacheResourceResponseProto struct {
	Path             *string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UseSharedCacheResourceResponseProto) Reset()         { *m = UseSharedCacheResourceResponseProto{} }
func (m *UseSharedCacheResourceResponseProto) String() string { return proto.CompactTextString(m) }
func (*UseSharedCacheResourceResponseProto) ProtoMessage()    {}
func (*UseSharedCacheResourceResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{55}
}

func (m *UseSharedCacheResourceResponseProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type ReleaseSharedCacheResourceRequestProto struct {
	ApplicationId    *ApplicationIdProto `protobuf:"bytes,1,opt,name=applicationId" json:"applicationId,omitempty"`
	ResourceKey      *string             `protobuf:"bytes,2,opt,name=resourceKey" json:"resourceKey,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ReleaseSharedCacheResourceRequestProto) Reset() {
	*m = ReleaseSharedCacheResourceRequestProto{}
}
func (m *ReleaseSharedCacheResourceRequestProto) String() string { return proto.CompactTextString(m) }
func (*ReleaseSharedCacheResourceRequestProto) ProtoMessage()    {}
func (*ReleaseSharedCacheResourceRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{56}
}

func (m *ReleaseSharedCacheResourceRequestProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *ReleaseSharedCacheResourceRequestProto) GetResourceKey() string {
	if m != nil && m.ResourceKey != nil {
		return *m.ResourceKey
	}
	return ""
}

type ReleaseSharedCacheResourceResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReleaseSharedCacheResourceResponseProto) Reset() {
	*m = ReleaseSharedCacheResourceResponseProto{}
}
func (m *ReleaseSharedCacheResourceResponseProto) String() string { return proto.CompactTextString(m) }
func (*ReleaseSharedCacheResourceResponseProto) ProtoMessage()    {}
func (*ReleaseSharedCacheResourceResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{57}
}

type ReservationSubmissionRequestProto struct {
	Queue                 *string                     `protobuf:"bytes,1,opt,name=queue" json:"queue,omitempty"`
	ReservationDefinition *ReservationDefinitionProto `protobuf:"bytes,2,opt,name=reservation_definition,json=reservationDefinition" json:"reservation_definition,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *ReservationSubmissionRequestProto) Reset()         { *m = ReservationSubmissionRequestProto{} }
func (m *ReservationSubmissionRequestProto) String() string { return proto.CompactTextString(m) }
func (*ReservationSubmissionRequestProto) ProtoMessage()    {}
func (*ReservationSubmissionRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{58}
}

func (m *ReservationSubmissionRequestProto) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

func (m *ReservationSubmissionRequestProto) GetReservationDefinition() *ReservationDefinitionProto {
	if m != nil {
		return m.ReservationDefinition
	}
	return nil
}

type ReservationSubmissionResponseProto struct {
	ReservationId    *ReservationIdProto `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId" json:"reservation_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ReservationSubmissionResponseProto) Reset()         { *m = ReservationSubmissionResponseProto{} }
func (m *ReservationSubmissionResponseProto) String() string { return proto.CompactTextString(m) }
func (*ReservationSubmissionResponseProto) ProtoMessage()    {}
func (*ReservationSubmissionResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{59}
}

func (m *ReservationSubmissionResponseProto) GetReservationId() *ReservationIdProto {
	if m != nil {
		return m.ReservationId
	}
	return nil
}

type ReservationUpdateRequestProto struct {
	ReservationDefinition *ReservationDefinitionProto `protobuf:"bytes,1,opt,name=reservation_definition,json=reservationDefinition" json:"reservation_definition,omitempty"`
	ReservationId         *ReservationIdProto         `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId" json:"reservation_id,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *ReservationUpdateRequestProto) Reset()                    { *m = ReservationUpdateRequestProto{} }
func (m *ReservationUpdateRequestProto) String() string            { return proto.CompactTextString(m) }
func (*ReservationUpdateRequestProto) ProtoMessage()               {}
func (*ReservationUpdateRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{60} }

func (m *ReservationUpdateRequestProto) GetReservationDefinition() *ReservationDefinitionProto {
	if m != nil {
		return m.ReservationDefinition
	}
	return nil
}

func (m *ReservationUpdateRequestProto) GetReservationId() *ReservationIdProto {
	if m != nil {
		return m.ReservationId
	}
	return nil
}

type ReservationUpdateResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReservationUpdateResponseProto) Reset()                    { *m = ReservationUpdateResponseProto{} }
func (m *ReservationUpdateResponseProto) String() string            { return proto.CompactTextString(m) }
func (*ReservationUpdateResponseProto) ProtoMessage()               {}
func (*ReservationUpdateResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{61} }

type ReservationDeleteRequestProto struct {
	ReservationId    *ReservationIdProto `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId" json:"reservation_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ReservationDeleteRequestProto) Reset()                    { *m = ReservationDeleteRequestProto{} }
func (m *ReservationDeleteRequestProto) String() string            { return proto.CompactTextString(m) }
func (*ReservationDeleteRequestProto) ProtoMessage()               {}
func (*ReservationDeleteRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{62} }

func (m *ReservationDeleteRequestProto) GetReservationId() *ReservationIdProto {
	if m != nil {
		return m.ReservationId
	}
	return nil
}

type ReservationDeleteResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReservationDeleteResponseProto) Reset()                    { *m = ReservationDeleteResponseProto{} }
func (m *ReservationDeleteResponseProto) String() string            { return proto.CompactTextString(m) }
func (*ReservationDeleteResponseProto) ProtoMessage()               {}
func (*ReservationDeleteResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{63} }

type RunSharedCacheCleanerTaskRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RunSharedCacheCleanerTaskRequestProto) Reset()         { *m = RunSharedCacheCleanerTaskRequestProto{} }
func (m *RunSharedCacheCleanerTaskRequestProto) String() string { return proto.CompactTextString(m) }
func (*RunSharedCacheCleanerTaskRequestProto) ProtoMessage()    {}
func (*RunSharedCacheCleanerTaskRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{64}
}

type RunSharedCacheCleanerTaskResponseProto struct {
	Accepted         *bool  `protobuf:"varint,1,opt,name=accepted" json:"accepted,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RunSharedCacheCleanerTaskResponseProto) Reset() {
	*m = RunSharedCacheCleanerTaskResponseProto{}
}
func (m *RunSharedCacheCleanerTaskResponseProto) String() string { return proto.CompactTextString(m) }
func (*RunSharedCacheCleanerTaskResponseProto) ProtoMessage()    {}
func (*RunSharedCacheCleanerTaskResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{65}
}

func (m *RunSharedCacheCleanerTaskResponseProto) GetAccepted() bool {
	if m != nil && m.Accepted != nil {
		return *m.Accepted
	}
	return false
}

func init() {
	proto.RegisterType((*RegisterApplicationMasterRequestProto)(nil), "hadoop.yarn.RegisterApplicationMasterRequestProto")
	proto.RegisterType((*RegisterApplicationMasterResponseProto)(nil), "hadoop.yarn.RegisterApplicationMasterResponseProto")
	proto.RegisterType((*FinishApplicationMasterRequestProto)(nil), "hadoop.yarn.FinishApplicationMasterRequestProto")
	proto.RegisterType((*FinishApplicationMasterResponseProto)(nil), "hadoop.yarn.FinishApplicationMasterResponseProto")
	proto.RegisterType((*AllocateRequestProto)(nil), "hadoop.yarn.AllocateRequestProto")
	proto.RegisterType((*NMTokenProto)(nil), "hadoop.yarn.NMTokenProto")
	proto.RegisterType((*AllocateResponseProto)(nil), "hadoop.yarn.AllocateResponseProto")
	proto.RegisterType((*GetNewApplicationRequestProto)(nil), "hadoop.yarn.GetNewApplicationRequestProto")
	proto.RegisterType((*GetNewApplicationResponseProto)(nil), "hadoop.yarn.GetNewApplicationResponseProto")
	proto.RegisterType((*GetApplicationReportRequestProto)(nil), "hadoop.yarn.GetApplicationReportRequestProto")
	proto.RegisterType((*GetApplicationReportResponseProto)(nil), "hadoop.yarn.GetApplicationReportResponseProto")
	proto.RegisterType((*SubmitApplicationRequestProto)(nil), "hadoop.yarn.SubmitApplicationRequestProto")
	proto.RegisterType((*SubmitApplicationResponseProto)(nil), "hadoop.yarn.SubmitApplicationResponseProto")
	proto.RegisterType((*KillApplicationRequestProto)(nil), "hadoop.yarn.KillApplicationRequestProto")
	proto.RegisterType((*KillApplicationResponseProto)(nil), "hadoop.yarn.KillApplicationResponseProto")
	proto.RegisterType((*GetClusterMetricsRequestProto)(nil), "hadoop.yarn.GetClusterMetricsRequestProto")
	proto.RegisterType((*GetClusterMetricsResponseProto)(nil), "hadoop.yarn.GetClusterMetricsResponseProto")
	proto.RegisterType((*MoveApplicationAcrossQueuesRequestProto)(nil), "hadoop.yarn.MoveApplicationAcrossQueuesRequestProto")
	proto.RegisterType((*MoveApplicationAcrossQueuesResponseProto)(nil), "hadoop.yarn.MoveApplicationAcrossQueuesResponseProto")
	proto.RegisterType((*GetApplicationsRequestProto)(nil), "hadoop.yarn.GetApplicationsRequestProto")
	proto.RegisterType((*GetApplicationsResponseProto)(nil), "hadoop.yarn.GetApplicationsResponseProto")
	proto.RegisterType((*GetClusterNodesRequestProto)(nil), "hadoop.yarn.GetClusterNodesRequestProto")
	proto.RegisterType((*GetClusterNodesResponseProto)(nil), "hadoop.yarn.GetClusterNodesResponseProto")
	proto.RegisterType((*GetQueueInfoRequestProto)(nil), "hadoop.yarn.GetQueueInfoRequestProto")
	proto.RegisterType((*GetQueueInfoResponseProto)(nil), "hadoop.yarn.GetQueueInfoResponseProto")
	proto.RegisterType((*GetQueueUserAclsInfoRequestProto)(nil), "hadoop.yarn.GetQueueUserAclsInfoRequestProto")
	proto.RegisterType((*GetQueueUserAclsInfoResponseProto)(nil), "hadoop.yarn.GetQueueUserAclsInfoResponseProto")
	proto.RegisterType((*GetNodesToLabelsRequestProto)(nil), "hadoop.yarn.GetNodesToLabelsRequestProto")
	proto.RegisterType((*GetNodesToLabelsResponseProto)(nil), "hadoop.yarn.GetNodesToLabelsResponseProto")
	proto.RegisterType((*GetLabelsToNodesRequestProto)(nil), "hadoop.yarn.GetLabelsToNodesRequestProto")
	proto.RegisterType((*GetLabelsToNodesResponseProto)(nil), "hadoop.yarn.GetLabelsToNodesResponseProto")
	proto.RegisterType((*GetClusterNodeLabelsRequestProto)(nil), "hadoop.yarn.GetClusterNodeLabelsRequestProto")
	proto.RegisterType((*GetClusterNodeLabelsResponseProto)(nil), "hadoop.yarn.GetClusterNodeLabelsResponseProto")
	proto.RegisterType((*StartContainerRequestProto)(nil), "hadoop.yarn.StartContainerRequestProto")
	proto.RegisterType((*StartContainerResponseProto)(nil), "hadoop.yarn.StartContainerResponseProto")
	proto.RegisterType((*StopContainerRequestProto)(nil), "hadoop.yarn.StopContainerRequestProto")
	proto.RegisterType((*StopContainerResponseProto)(nil), "hadoop.yarn.StopContainerResponseProto")
	proto.RegisterType((*GetContainerStatusRequestProto)(nil), "hadoop.yarn.GetContainerStatusRequestProto")
	proto.RegisterType((*GetContainerStatusResponseProto)(nil), "hadoop.yarn.GetContainerStatusResponseProto")
	proto.RegisterType((*StartContainersRequestProto)(nil), "hadoop.yarn.StartContainersRequestProto")
	proto.RegisterType((*ContainerExceptionMapProto)(nil), "hadoop.yarn.ContainerExceptionMapProto")
	proto.RegisterType((*StartContainersResponseProto)(nil), "hadoop.yarn.StartContainersResponseProto")
	proto.RegisterType((*StopContainersRequestProto)(nil), "hadoop.yarn.StopContainersRequestProto")
	proto.RegisterType((*StopContainersResponseProto)(nil), "hadoop.yarn.StopContainersResponseProto")
	proto.RegisterType((*GetContainerStatusesRequestProto)(nil), "hadoop.yarn.GetContainerStatusesRequestProto")
	proto.RegisterType((*GetContainerStatusesResponseProto)(nil), "hadoop.yarn.GetContainerStatusesResponseProto")
	proto.RegisterType((*GetApplicationAttemptReportRequestProto)(nil), "hadoop.yarn.GetApplicationAttemptReportRequestProto")
	proto.RegisterType((*GetApplicationAttemptReportResponseProto)(nil), "hadoop.yarn.GetApplicationAttemptReportResponseProto")
	proto.RegisterType((*GetApplicationAttemptsRequestProto)(nil), "hadoop.yarn.GetApplicationAttemptsRequestProto")
	proto.RegisterType((*GetApplicationAttemptsResponseProto)(nil), "hadoop.yarn.GetApplicationAttemptsResponseProto")
	proto.RegisterType((*GetContainerReportRequestProto)(nil), "hadoop.yarn.GetContainerReportRequestProto")
	proto.RegisterType((*GetContainerReportResponseProto)(nil), "hadoop.yarn.GetContainerReportResponseProto")
	proto.RegisterType((*GetContainersRequestProto)(nil), "hadoop.yarn.GetContainersRequestProto")
	proto.RegisterType((*GetContainersResponseProto)(nil), "hadoop.yarn.GetContainersResponseProto")
	proto.RegisterType((*UseSharedCacheResourceRequestProto)(nil), "hadoop.yarn.UseSharedCacheResourceRequestProto")
	proto.RegisterType((*UseSharedCacheResourceResponseProto)(nil), "hadoop.yarn.UseSharedCacheResourceResponseProto")
	proto.RegisterType((*ReleaseSharedCacheResourceRequestProto)(nil), "hadoop.yarn.ReleaseSharedCacheResourceRequestProto")
	proto.RegisterType((*ReleaseSharedCacheResourceResponseProto)(nil), "hadoop.yarn.ReleaseSharedCacheResourceResponseProto")
	proto.RegisterType((*ReservationSubmissionRequestProto)(nil), "hadoop.yarn.ReservationSubmissionRequestProto")
	proto.RegisterType((*ReservationSubmissionResponseProto)(nil), "hadoop.yarn.ReservationSubmissionResponseProto")
	proto.RegisterType((*ReservationUpdateRequestProto)(nil), "hadoop.yarn.ReservationUpdateRequestProto")
	proto.RegisterType((*ReservationUpdateResponseProto)(nil), "hadoop.yarn.ReservationUpdateResponseProto")
	proto.RegisterType((*ReservationDeleteRequestProto)(nil), "hadoop.yarn.ReservationDeleteRequestProto")
	proto.RegisterType((*ReservationDeleteResponseProto)(nil), "hadoop.yarn.ReservationDeleteResponseProto")
	proto.RegisterType((*RunSharedCacheCleanerTaskRequestProto)(nil), "hadoop.yarn.RunSharedCacheCleanerTaskRequestProto")
	proto.RegisterType((*RunSharedCacheCleanerTaskResponseProto)(nil), "hadoop.yarn.RunSharedCacheCleanerTaskResponseProto")
	proto.RegisterEnum("hadoop.yarn.SchedulerResourceTypes", SchedulerResourceTypes_name, SchedulerResourceTypes_value)
	proto.RegisterEnum("hadoop.yarn.ApplicationsRequestScopeProto", ApplicationsRequestScopeProto_name, ApplicationsRequestScopeProto_value)
}

func init() { proto.RegisterFile("yarn_service_protos.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 2535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x1a, 0x4b, 0x6f, 0x1c, 0x49,
	0x79, 0x7b, 0x26, 0xb6, 0x67, 0xbe, 0x71, 0xfc, 0xe8, 0xf5, 0x9a, 0x89, 0x63, 0x3b, 0xe3, 0xce,
	0x6e, 0x6c, 0xbc, 0x5a, 0x13, 0x8c, 0xc4, 0x2a, 0xbb, 0x62, 0x97, 0xf1, 0xc4, 0x09, 0x56, 0xc6,
	0x5e, 0x6f, 0xdb, 0xde, 0x28, 0x68, 0x93, 0xa6, 0xdc, 0x5d, 0x1e, 0x37, 0xee, 0xc7, 0xa4, 0xaa,
	0x27, 0x1b, 0x73, 0xe0, 0x84, 0x04, 0x17, 0x90, 0x90, 0xe0, 0xc0, 0x0d, 0x89, 0x3f, 0x80, 0x38,
	0x71, 0xd9, 0x13, 0x48, 0xdc, 0x38, 0xf2, 0x5f, 0xb8, 0xa1, 0x7a, 0x74, 0x4f, 0x55, 0x4f, 0xcf,
	0xd8, 0x49, 0x1c, 0x89, 0x53, 0x3c, 0xdf, 0xfb, 0x5d, 0x5f, 0x55, 0x07, 0x6e, 0x9c, 0x23, 0x12,
	0x39, 0x14, 0x93, 0x17, 0xbe, 0x8b, 0x9d, 0x2e, 0x89, 0x93, 0x98, 0x6e, 0xf0, 0x7f, 0xcc, 0xda,
	0x29, 0xf2, 0xe2, 0xb8, 0xbb, 0xc1, 0x28, 0x16, 0xa6, 0x0e, 0xb0, 0xdb, 0x23, 0x7e, 0x72, 0x2e,
	0x90, 0x0b, 0xb3, 0x9c, 0x4f, 0xa5, 0xb7, 0xce, 0xe1, 0x03, 0x1b, 0x77, 0x7c, 0x9a, 0x60, 0xd2,
	0xec, 0x76, 0x03, 0xdf, 0x45, 0x89, 0x1f, 0x47, 0xbb, 0x88, 0x01, 0x6c, 0xfc, 0xbc, 0x87, 0x69,
	0xb2, 0xcf, 0x05, 0x9b, 0x70, 0xed, 0x34, 0xa6, 0x49, 0xdd, 0x68, 0x18, 0x6b, 0x55, 0x9b, 0xff,
	0x6d, 0xde, 0x80, 0x0a, 0xe9, 0xba, 0x4e, 0x37, 0x26, 0x49, 0xbd, 0xd4, 0x30, 0xd6, 0xc6, 0xec,
	0x09, 0xd2, 0x75, 0xf7, 0x63, 0x92, 0x98, 0x2b, 0x30, 0x99, 0x10, 0xe4, 0x9e, 0xf9, 0x51, 0xc7,
	0xe9, 0x91, 0xa0, 0x5e, 0xe6, 0x6c, 0xb5, 0x14, 0x76, 0x44, 0x02, 0xeb, 0x1f, 0xd7, 0xe0, 0xce,
	0x08, 0xdd, 0xb4, 0x1b, 0x47, 0x14, 0x0b, 0xe5, 0x3f, 0x81, 0xd9, 0x10, 0xbd, 0xf4, 0xc3, 0x5e,
	0xd8, 0x42, 0x5d, 0x74, 0xec, 0x07, 0x7e, 0x72, 0xce, 0x2d, 0xa9, 0x6d, 0x2e, 0x6c, 0x28, 0x1e,
	0x6f, 0xd8, 0x98, 0xc6, 0x3d, 0xe2, 0x0a, 0x36, 0x7b, 0x90, 0xc9, 0xfc, 0x1c, 0x96, 0xdc, 0xc0,
	0xc7, 0x51, 0xe2, 0x24, 0xb1, 0x83, 0x42, 0x27, 0x89, 0xcf, 0x70, 0xe4, 0x84, 0x5c, 0xa7, 0x73,
	0x86, 0xcf, 0xb9, 0x1f, 0x93, 0x76, 0x5d, 0x10, 0x1d, 0xc6, 0xcd, 0xf0, 0x90, 0x51, 0x08, 0xa3,
	0x1e, 0xe1, 0x73, 0x73, 0x0f, 0x66, 0x50, 0xdf, 0x58, 0xa7, 0xd9, 0x6a, 0xd3, 0x7a, 0xb9, 0x51,
	0x5e, 0xab, 0x6d, 0xde, 0xd6, 0x2c, 0x51, 0x3c, 0x6a, 0xb6, 0xda, 0xbb, 0xa8, 0x2b, 0x4c, 0x9a,
	0x46, 0x1a, 0x9c, 0x9a, 0x27, 0xb0, 0xe2, 0xc6, 0x51, 0x82, 0xfc, 0x08, 0x13, 0xea, 0x9c, 0x90,
	0x38, 0x74, 0xba, 0x04, 0xbf, 0xf0, 0xe3, 0x1e, 0x75, 0x50, 0x92, 0xe0, 0xb0, 0x9b, 0xd0, 0xfa,
	0x35, 0xae, 0xe0, 0xa6, 0xa6, 0xa0, 0x95, 0x72, 0x09, 0xc1, 0xcb, 0x7d, 0x29, 0x0f, 0x48, 0x1c,
	0xee, 0x4b, 0x19, 0x4d, 0x29, 0xc2, 0x9c, 0x83, 0xb1, 0xe7, 0x3d, 0xdc, 0xc3, 0xf5, 0x31, 0x9e,
	0x09, 0xf1, 0xc3, 0x44, 0xd0, 0x88, 0x64, 0x10, 0x86, 0x2a, 0x1f, 0xe7, 0xca, 0x6f, 0x68, 0xca,
	0xf7, 0x76, 0x79, 0x58, 0x84, 0xea, 0xc5, 0x48, 0x04, 0xa9, 0x58, 0xf1, 0x53, 0xa8, 0x53, 0xf7,
	0x14, 0x7b, 0xbd, 0x00, 0x13, 0x87, 0xc8, 0xfc, 0x38, 0xc9, 0x79, 0x17, 0xd3, 0xfa, 0x44, 0xa3,
	0xbc, 0x36, 0x95, 0x0b, 0xdc, 0x41, 0x4a, 0x9c, 0xe6, 0xf2, 0x90, 0x91, 0xda, 0xf3, 0xb4, 0x10,
	0x6e, 0xfd, 0xdb, 0x80, 0xdb, 0x0f, 0xfc, 0xc8, 0xa7, 0xa7, 0xa3, 0xeb, 0xb7, 0x01, 0x35, 0xcf,
	0x47, 0x9d, 0x28, 0xa6, 0x89, 0xef, 0x52, 0x59, 0xc6, 0x2a, 0x68, 0xa0, 0x64, 0x4b, 0x03, 0x25,
	0x6b, 0x1e, 0x43, 0xfd, 0xc4, 0x8f, 0x50, 0xe0, 0xa8, 0x25, 0x40, 0x13, 0x94, 0xf4, 0x28, 0xaf,
	0xf0, 0xa9, 0xcd, 0x35, 0xcd, 0x97, 0x07, 0x8c, 0x58, 0xb1, 0xeb, 0x80, 0x93, 0x8a, 0xa8, 0xcd,
	0x9f, 0x14, 0x22, 0xad, 0x23, 0x78, 0x7f, 0xa8, 0x3f, 0x6a, 0x4f, 0x7c, 0x04, 0x53, 0x3e, 0x3d,
	0x8a, 0x88, 0xec, 0x20, 0xec, 0x71, 0x9f, 0x2a, 0x9f, 0x8c, 0x9d, 0xa0, 0x80, 0x62, 0x3b, 0x87,
	0xb4, 0xfe, 0x5b, 0x82, 0xb9, 0x66, 0x10, 0xc4, 0x2e, 0x4a, 0xb0, 0x16, 0x98, 0x1f, 0x40, 0x19,
	0xd1, 0xb3, 0xba, 0xc1, 0xb3, 0xbc, 0x52, 0xd8, 0x4d, 0x2a, 0xbd, 0xcd, 0xa8, 0xcd, 0x8f, 0x61,
	0x82, 0xe0, 0x00, 0x23, 0x8a, 0xeb, 0x25, 0xce, 0xb8, 0x54, 0x5c, 0x9b, 0x3b, 0x9e, 0x60, 0x4a,
	0xa9, 0xcd, 0xc7, 0x30, 0x7b, 0x1c, 0x20, 0xf7, 0x2c, 0xf0, 0x69, 0xe2, 0x10, 0x21, 0x97, 0x87,
	0xae, 0xb6, 0xb9, 0x5e, 0xa8, 0x7b, 0x2b, 0xa5, 0xd6, 0x8c, 0x98, 0x39, 0xce, 0x81, 0xcd, 0x5b,
	0x50, 0x23, 0x32, 0x3e, 0x8e, 0xef, 0xd5, 0xaf, 0xf1, 0x71, 0x04, 0x29, 0x68, 0xc7, 0x33, 0x17,
	0xa0, 0xd2, 0x25, 0x71, 0x87, 0x60, 0x4a, 0x79, 0x0f, 0x94, 0xec, 0xec, 0xb7, 0xf9, 0x14, 0x66,
	0xfc, 0xc8, 0x25, 0xcc, 0xc2, 0xcc, 0x28, 0x51, 0xf6, 0x9b, 0xc5, 0x7e, 0xa5, 0xd6, 0xed, 0x48,
	0x2e, 0xcd, 0xb8, 0x69, 0x5f, 0x87, 0x5a, 0xcf, 0x61, 0x52, 0x6d, 0x18, 0xf3, 0x2e, 0x8c, 0x47,
	0xb1, 0x87, 0x77, 0x3c, 0x39, 0xc3, 0xea, 0x7a, 0x6f, 0x71, 0x94, 0x10, 0x25, 0xe9, 0xcc, 0xef,
	0xc1, 0x18, 0x6f, 0x52, 0x5e, 0x94, 0x4a, 0x33, 0xba, 0x71, 0x18, 0xc6, 0xd1, 0x86, 0xd2, 0x8c,
	0x82, 0xce, 0xfa, 0x76, 0x1c, 0xde, 0xeb, 0xa7, 0x5b, 0xad, 0x9b, 0x4f, 0xa1, 0x86, 0x9c, 0xd0,
	0x61, 0x9c, 0x28, 0x12, 0x16, 0x4c, 0xe5, 0x46, 0x4b, 0x73, 0xb7, 0x25, 0xb0, 0x42, 0x64, 0x15,
	0xa5, 0xbf, 0xf3, 0x51, 0x2e, 0x0d, 0x44, 0x79, 0x0f, 0xe6, 0x90, 0x54, 0xeb, 0x39, 0xfd, 0x91,
	0x24, 0x47, 0xe4, 0xc8, 0x09, 0xf6, 0x6e, 0xc6, 0x98, 0x21, 0xa8, 0xe9, 0xc2, 0xa2, 0x1b, 0x87,
	0xdd, 0x00, 0x6b, 0xf2, 0x64, 0xcf, 0xe1, 0x74, 0x32, 0xae, 0x14, 0xcb, 0x55, 0xdb, 0x6d, 0x21,
	0x13, 0x93, 0x43, 0x63, 0x6a, 0xde, 0x85, 0xb1, 0xc0, 0x0f, 0xfd, 0x84, 0xd7, 0xc5, 0xe8, 0x23,
	0x45, 0x10, 0x9a, 0x4d, 0xb8, 0xde, 0xeb, 0x7a, 0xdc, 0x49, 0x96, 0xa1, 0x74, 0x48, 0x2e, 0x0e,
	0x24, 0xd2, 0xc6, 0xec, 0x74, 0x14, 0xbc, 0x93, 0x92, 0x85, 0xc1, 0xa9, 0xb9, 0x0e, 0xb3, 0x51,
	0x2f, 0x74, 0xdc, 0xa0, 0xc7, 0xcf, 0x1e, 0x21, 0x66, 0x82, 0x07, 0x74, 0x3a, 0xea, 0x85, 0x2d,
	0x01, 0x17, 0xb4, 0x3f, 0x82, 0x89, 0x2e, 0xc1, 0x6c, 0x9e, 0xd6, 0x2b, 0xdc, 0x44, 0x7d, 0x64,
	0xee, 0x0b, 0x1c, 0x1b, 0x14, 0x98, 0x52, 0xd4, 0x91, 0xb6, 0xa6, 0x3c, 0xe6, 0x0f, 0xa1, 0x9a,
	0x4d, 0xf9, 0x7a, 0xf5, 0xa2, 0x71, 0x5e, 0x49, 0xc7, 0xb9, 0xf9, 0x0c, 0xe6, 0xd2, 0x52, 0xd6,
	0x92, 0x09, 0x5c, 0xc4, 0x87, 0x97, 0x6b, 0x0d, 0x99, 0xdc, 0x4c, 0x90, 0x92, 0xdc, 0x67, 0x30,
	0xe7, 0xe1, 0x02, 0xf9, 0xb5, 0xcb, 0xc8, 0xbf, 0x8f, 0x35, 0xf9, 0x99, 0x20, 0x45, 0xfe, 0x3d,
	0xa8, 0xa1, 0xd0, 0x21, 0xd2, 0xf5, 0xfa, 0xe4, 0x45, 0xbd, 0x53, 0x45, 0xa1, 0x2d, 0x7c, 0xb7,
	0x6e, 0xc1, 0xd2, 0x43, 0x9c, 0xec, 0xe1, 0x6f, 0x94, 0x29, 0xac, 0x36, 0xb9, 0xf5, 0x37, 0x03,
	0x96, 0x0b, 0x28, 0xd4, 0x4e, 0x7b, 0x00, 0x53, 0xea, 0x39, 0xe1, 0xa7, 0xed, 0x7e, 0x6b, 0xd8,
	0xa2, 0x90, 0x76, 0xfd, 0x75, 0xa4, 0xc2, 0x8a, 0xb7, 0x9f, 0xd2, 0x6b, 0x6c, 0x3f, 0xd6, 0xcf,
	0xa1, 0xf1, 0x10, 0x27, 0x9a, 0xc1, 0xac, 0x3c, 0xb5, 0xf3, 0xe0, 0x8a, 0xac, 0xb6, 0xbe, 0x81,
	0x95, 0x62, 0x5d, 0x6a, 0x88, 0x6c, 0x30, 0x55, 0x65, 0x84, 0x93, 0x48, 0x85, 0x43, 0xf7, 0x29,
	0xb5, 0xa7, 0x66, 0x51, 0x1e, 0x6e, 0xfd, 0xd1, 0x80, 0xa5, 0x83, 0xde, 0x71, 0xe8, 0x27, 0x43,
	0x72, 0x67, 0x26, 0xb0, 0xac, 0x1d, 0xe0, 0x8c, 0x98, 0x52, 0xf6, 0x27, 0x2b, 0x42, 0xfc, 0x32,
	0xb5, 0x60, 0x63, 0x98, 0x05, 0x07, 0x19, 0x47, 0x4b, 0x30, 0xc8, 0x45, 0x08, 0x8d, 0x20, 0xb1,
	0x1a, 0xb0, 0x5c, 0x60, 0x96, 0x12, 0x0d, 0x0b, 0xc3, 0xcd, 0x47, 0x7e, 0x10, 0x0c, 0x33, 0xfb,
	0xaa, 0x32, 0xf3, 0x25, 0x2c, 0x0e, 0xa8, 0x51, 0x93, 0xf2, 0x7d, 0x98, 0xf5, 0xa9, 0x73, 0xe6,
	0x07, 0x81, 0x93, 0x0d, 0x4d, 0x7d, 0xb9, 0x98, 0xf6, 0x29, 0x93, 0xd0, 0x4a, 0xb1, 0xb2, 0x5d,
	0xe4, 0xcc, 0xda, 0xc5, 0x09, 0xf1, 0x5d, 0xaa, 0xb5, 0x4b, 0xcc, 0xbb, 0x25, 0x4f, 0xa0, 0x6a,
	0xdd, 0x85, 0xe9, 0x74, 0x16, 0x86, 0x02, 0x2f, 0xdd, 0x7b, 0x5f, 0x73, 0xef, 0x09, 0x22, 0x91,
	0x2e, 0x46, 0xf8, 0x38, 0xe5, 0x6a, 0x40, 0xeb, 0x0f, 0x06, 0xac, 0xee, 0xc6, 0x2f, 0xb0, 0xba,
	0x87, 0xbb, 0x24, 0xa6, 0xf4, 0x4b, 0xb6, 0xf8, 0xd2, 0x0b, 0x03, 0x5b, 0x7a, 0x8d, 0x46, 0x65,
	0x1b, 0x24, 0x22, 0x1d, 0x9c, 0x38, 0x62, 0xd5, 0x2e, 0x35, 0x4a, 0x7c, 0x83, 0xe4, 0x30, 0xae,
	0xd7, 0x5a, 0x87, 0xb5, 0x91, 0x56, 0xa9, 0xe5, 0xf0, 0x9f, 0x32, 0xdc, 0xd4, 0x5b, 0x48, 0x37,
	0xfb, 0x43, 0x50, 0xab, 0x5f, 0xae, 0xd4, 0x6c, 0x8f, 0xab, 0xda, 0xea, 0x1d, 0x85, 0xef, 0xc9,
	0xe6, 0x91, 0xde, 0x69, 0xec, 0x00, 0xc5, 0x94, 0x2f, 0x6f, 0x53, 0x9b, 0x77, 0x06, 0x22, 0x9c,
	0x5b, 0x4b, 0xf1, 0x60, 0xb3, 0x71, 0x30, 0xbf, 0x56, 0xf4, 0x68, 0x7a, 0xc0, 0x57, 0x6d, 0xf1,
	0xc3, 0x9c, 0x87, 0x71, 0x1e, 0x01, 0x71, 0x3e, 0x57, 0x6d, 0xf9, 0x8b, 0x51, 0xf7, 0x0f, 0xda,
	0x72, 0x7a, 0x98, 0xde, 0x82, 0x1a, 0x4d, 0x10, 0x49, 0x9c, 0x63, 0xdc, 0xf1, 0xa3, 0xfa, 0x38,
	0xc7, 0x01, 0x07, 0x6d, 0x31, 0x88, 0x79, 0x13, 0xaa, 0x82, 0x00, 0x47, 0x1e, 0x3f, 0x22, 0xcb,
	0x76, 0x85, 0x03, 0xb6, 0x23, 0x1e, 0xf4, 0x13, 0xbe, 0x2f, 0x4b, 0xf6, 0x0a, 0xc7, 0xd7, 0x04,
	0x4c, 0xf0, 0x2f, 0x01, 0x48, 0x12, 0x26, 0xa0, 0xca, 0x09, 0xaa, 0x02, 0xc2, 0x24, 0xac, 0x81,
	0x7a, 0x2b, 0x3b, 0x44, 0x1d, 0x71, 0xc2, 0x55, 0xed, 0x3c, 0xd8, 0xdc, 0x86, 0x31, 0xea, 0xc6,
	0x5d, 0x5c, 0xaf, 0xf1, 0xad, 0x69, 0x7d, 0x58, 0x7d, 0xa4, 0x79, 0x3a, 0x60, 0xc4, 0x3c, 0x76,
	0x9f, 0x94, 0x9b, 0xed, 0xb6, 0x2d, 0xb8, 0xad, 0x0e, 0x2c, 0x0e, 0xe4, 0x55, 0x6d, 0x85, 0x87,
	0x30, 0xa9, 0x68, 0xa6, 0x72, 0x37, 0xbf, 0xd4, 0x3c, 0xd4, 0x18, 0xad, 0x9f, 0xf2, 0x02, 0x52,
	0x57, 0x09, 0xad, 0x80, 0x3e, 0x05, 0x60, 0x6b, 0x87, 0x48, 0x25, 0xd7, 0x92, 0xdf, 0x04, 0xf7,
	0x52, 0xb4, 0x90, 0xae, 0x90, 0x5b, 0xcf, 0xb8, 0x13, 0xba, 0x6c, 0xd5, 0x89, 0xcf, 0xa0, 0x16,
	0x65, 0x0b, 0x50, 0xea, 0xc3, 0xe8, 0x05, 0x49, 0x65, 0xb0, 0xfe, 0x6e, 0x40, 0xfd, 0xa1, 0x6c,
	0x9b, 0x9d, 0xe8, 0x24, 0xd6, 0x2c, 0x5f, 0x84, 0x2a, 0x2f, 0xa9, 0x3d, 0x14, 0x62, 0x79, 0x97,
	0xeb, 0x03, 0xcc, 0xbb, 0xc0, 0xd6, 0x8d, 0xa0, 0xe7, 0xa9, 0x7d, 0x46, 0xf9, 0x91, 0x59, 0xb1,
	0x8b, 0x50, 0xe6, 0x06, 0x98, 0x12, 0xdc, 0x3a, 0xf5, 0x03, 0x4f, 0x74, 0x23, 0xbf, 0x97, 0x54,
	0xec, 0x02, 0x0c, 0xd3, 0x4f, 0xb0, 0xdb, 0x23, 0xd4, 0x7f, 0x81, 0xf9, 0x5d, 0xa3, 0x62, 0xf7,
	0x01, 0xd6, 0x57, 0x70, 0x43, 0xb7, 0x5c, 0x8d, 0xcb, 0x3d, 0x69, 0x3a, 0xc3, 0xc8, 0x09, 0xa7,
	0xc7, 0x3c, 0xe3, 0x93, 0x4b, 0x49, 0x46, 0x6d, 0x59, 0xfc, 0xf8, 0xe6, 0xf8, 0x23, 0x8a, 0x49,
	0xd3, 0x0d, 0x68, 0x3e, 0x32, 0x56, 0xc8, 0x8f, 0xdd, 0x02, 0x1a, 0xfd, 0x3d, 0xe5, 0xfa, 0x73,
	0x95, 0x42, 0x66, 0xc7, 0x1a, 0xb4, 0x83, 0x53, 0xb4, 0xda, 0x7d, 0x73, 0x74, 0x46, 0x6b, 0x99,
	0x57, 0x01, 0x4f, 0xff, 0x61, 0xdc, 0x46, 0xc7, 0x38, 0xd0, 0xe7, 0xbe, 0x2f, 0xf6, 0x28, 0x1d,
	0xaf, 0x9b, 0x32, 0xc9, 0xb2, 0x9e, 0x22, 0xa5, 0x25, 0xef, 0x17, 0xdc, 0x88, 0x52, 0x92, 0xbe,
	0x2d, 0x1a, 0xa7, 0xf5, 0x19, 0x37, 0x45, 0xfc, 0x38, 0x8c, 0x07, 0xab, 0x7d, 0x59, 0x54, 0xbb,
	0xa2, 0xa7, 0x6a, 0x2b, 0x10, 0xeb, 0x94, 0x9b, 0x9a, 0xe3, 0xd7, 0xdb, 0xf2, 0x7a, 0xa0, 0x62,
	0x0b, 0xef, 0xcc, 0x2a, 0xff, 0x8e, 0x27, 0x0f, 0x27, 0x9d, 0x4f, 0xe6, 0x51, 0x69, 0x9d, 0x82,
	0xc0, 0xfd, 0x8c, 0xe7, 0xb1, 0x80, 0x46, 0xbf, 0xcb, 0xe5, 0x5d, 0xaa, 0x15, 0x34, 0x30, 0x47,
	0x2b, 0x0d, 0x2c, 0xfd, 0xfd, 0xa7, 0x01, 0x0b, 0x07, 0x6c, 0x8a, 0x2a, 0xab, 0xb5, 0x12, 0xae,
	0x63, 0xa8, 0xf7, 0xef, 0x5b, 0x01, 0xea, 0x45, 0xee, 0x69, 0x6e, 0x3d, 0x5a, 0x2b, 0x5e, 0xd0,
	0xdb, 0x9c, 0x56, 0x5b, 0x8c, 0xe6, 0xdd, 0x42, 0xa4, 0xb9, 0x05, 0xd3, 0x7d, 0x1d, 0x97, 0xbc,
	0xe0, 0x4e, 0x65, 0x1c, 0x62, 0x53, 0x0f, 0xe1, 0x66, 0xde, 0x0b, 0x35, 0x44, 0x7b, 0x60, 0xca,
	0x87, 0x52, 0xca, 0xf6, 0x0a, 0xe4, 0x78, 0x28, 0x41, 0x32, 0x54, 0x0d, 0xfd, 0xe1, 0x29, 0x21,
	0x7e, 0xd4, 0xd9, 0x3a, 0x4f, 0x30, 0xcd, 0x9e, 0xeb, 0x66, 0x52, 0xde, 0x5d, 0x9c, 0xa0, 0xfb,
	0x28, 0x41, 0xd6, 0x53, 0xb8, 0x71, 0x90, 0xc4, 0xdd, 0xe2, 0x98, 0xfd, 0x18, 0x26, 0xfb, 0xfe,
	0x64, 0xfb, 0xd9, 0x05, 0x6f, 0x23, 0x35, 0xb7, 0x0f, 0xb1, 0x16, 0x59, 0x4e, 0x34, 0xf1, 0xea,
	0x46, 0x70, 0x2c, 0xb6, 0x28, 0xfd, 0x02, 0x7b, 0xc5, 0x16, 0x7c, 0x0d, 0xb7, 0x8a, 0x74, 0xe8,
	0x23, 0x6c, 0x5c, 0x3e, 0x7a, 0x09, 0xf1, 0x97, 0xb8, 0x7e, 0x4b, 0x06, 0xeb, 0x97, 0xf9, 0x6c,
	0xe9, 0xe6, 0x3b, 0xf0, 0x1d, 0x71, 0xd2, 0xf7, 0x9d, 0x48, 0xdf, 0x63, 0x44, 0xca, 0x56, 0x73,
	0x29, 0x1b, 0x56, 0xbe, 0xf6, 0x7b, 0xb4, 0x08, 0x67, 0xfd, 0xc5, 0x80, 0x85, 0x0c, 0xb8, 0xfd,
	0xd2, 0xc5, 0xe2, 0xda, 0x2c, 0xf3, 0xfd, 0xe6, 0xe1, 0x33, 0x5b, 0x50, 0xc5, 0xa9, 0x58, 0x59,
	0xcc, 0x1f, 0xe8, 0x36, 0x63, 0xe2, 0xa3, 0xc0, 0xff, 0x05, 0xf6, 0x32, 0xf5, 0x72, 0xd0, 0x67,
	0x7c, 0xd6, 0xef, 0x4a, 0xb0, 0x38, 0x10, 0xa6, 0xb7, 0x58, 0xd5, 0x66, 0x1b, 0x4c, 0xda, 0x73,
	0x5d, 0x8c, 0x3d, 0xec, 0xa5, 0x11, 0xa7, 0x97, 0x7b, 0xda, 0x9b, 0xcd, 0x18, 0x65, 0x8c, 0xa9,
	0xb9, 0x0f, 0xd3, 0x27, 0xc8, 0x0f, 0x54, 0x51, 0xe5, 0x82, 0xec, 0x0d, 0xcf, 0x83, 0x3d, 0x25,
	0xf8, 0x53, 0x89, 0xd6, 0xb3, 0x5c, 0x5b, 0x5c, 0x54, 0xf4, 0xe5, 0x57, 0x2c, 0xfa, 0x6f, 0x0d,
	0x56, 0x97, 0xba, 0x02, 0x35, 0xde, 0xc5, 0xf1, 0x31, 0xae, 0x2e, 0x3e, 0xa5, 0x37, 0x8b, 0x8f,
	0x27, 0x4e, 0x94, 0xfc, 0xcb, 0xd6, 0x15, 0x47, 0xe9, 0xaf, 0x86, 0x38, 0x94, 0x06, 0xd5, 0x0c,
	0x9b, 0x0e, 0xe5, 0x57, 0x9a, 0x0e, 0x6f, 0x21, 0x30, 0xbf, 0x36, 0x60, 0x55, 0xdf, 0xb5, 0xe5,
	0x87, 0x89, 0x82, 0x97, 0x8f, 0xaf, 0x61, 0x5e, 0xbd, 0x22, 0xc9, 0x0f, 0x20, 0xfd, 0x31, 0x70,
	0x67, 0xe8, 0x07, 0x1e, 0x41, 0x99, 0xc6, 0x6c, 0x0e, 0x15, 0xa0, 0xd8, 0x85, 0x74, 0x6d, 0xa4,
	0x25, 0x6a, 0x0c, 0x4f, 0x61, 0xa1, 0xc8, 0x14, 0xed, 0x7d, 0x64, 0xfd, 0x02, 0x73, 0xd4, 0xcd,
	0xba, 0x8e, 0x86, 0xa0, 0xad, 0x00, 0xac, 0x42, 0xab, 0xe8, 0x5b, 0x79, 0x7a, 0xf8, 0x95, 0x01,
	0xb7, 0x87, 0xa9, 0x53, 0xfd, 0x7f, 0x0a, 0x73, 0x05, 0xfe, 0xa7, 0x15, 0xf5, 0x2a, 0x9e, 0xbf,
	0x3b, 0xe8, 0x39, 0xcd, 0x9f, 0xa3, 0x05, 0xb5, 0xf0, 0xe6, 0xe7, 0x68, 0xac, 0x9f, 0xa3, 0x45,
	0x59, 0x6e, 0xc3, 0x8c, 0x7a, 0xce, 0x29, 0xb9, 0x5d, 0x19, 0xf6, 0xf6, 0xd9, 0x77, 0xac, 0xbf,
	0x39, 0xc9, 0x4c, 0x9e, 0xf3, 0x5b, 0xc7, 0x90, 0x11, 0xf9, 0x76, 0x6b, 0xdb, 0x81, 0x85, 0x9c,
	0x6a, 0xd5, 0xcd, 0x26, 0x80, 0xf2, 0xb8, 0x3b, 0x72, 0x28, 0xa8, 0x0e, 0x2a, 0x4c, 0xd6, 0x6f,
	0x0d, 0xb0, 0x8e, 0x28, 0x3e, 0x38, 0x45, 0x04, 0x7b, 0x2d, 0xe4, 0x9e, 0xe2, 0xa2, 0x6f, 0x53,
	0xe6, 0x36, 0xe8, 0xf5, 0xf6, 0x9a, 0x0f, 0xae, 0x0d, 0xfe, 0x95, 0x83, 0x8b, 0x7f, 0x24, 0x3f,
	0x09, 0x57, 0x6d, 0x15, 0x64, 0xdd, 0x83, 0xdb, 0xc3, 0xcc, 0x51, 0x3d, 0x37, 0xe1, 0x5a, 0x17,
	0x25, 0xa7, 0xe9, 0x47, 0x73, 0xf6, 0xb7, 0xf5, 0x7b, 0x03, 0xee, 0xd8, 0xe2, 0x6b, 0xd8, 0xff,
	0x8d, 0x3b, 0xdf, 0x85, 0xd5, 0x51, 0x26, 0xa9, 0x2b, 0xe8, 0x9f, 0x0c, 0x58, 0xb1, 0x31, 0x5b,
	0x20, 0x72, 0xcf, 0x9c, 0x9a, 0xe5, 0xd9, 0xd7, 0x66, 0x43, 0xfd, 0xda, 0xfc, 0x0c, 0xe6, 0x49,
	0x9f, 0xd5, 0xf1, 0xf0, 0x89, 0x1f, 0xf9, 0xca, 0xa2, 0xb4, 0x9a, 0x7f, 0xcd, 0x4e, 0x49, 0xef,
	0x67, 0x94, 0x72, 0xb9, 0x23, 0x45, 0x38, 0x36, 0xcb, 0x86, 0x98, 0x96, 0x7b, 0x96, 0x57, 0xad,
	0x18, 0x32, 0xcb, 0x14, 0x41, 0x59, 0x58, 0x89, 0x0a, 0xb3, 0xfe, 0x65, 0xc0, 0x92, 0x42, 0x75,
	0xc4, 0x3f, 0xee, 0x68, 0x51, 0x18, 0xee, 0xaf, 0x71, 0x15, 0xfe, 0x16, 0x78, 0x52, 0x7a, 0x2d,
	0x4f, 0x1a, 0xb0, 0x5c, 0xe0, 0x88, 0x9a, 0xf5, 0x8e, 0xe6, 0xea, 0x7d, 0x1c, 0xe0, 0x9c, 0xab,
	0x57, 0x15, 0x54, 0xdd, 0x94, 0x54, 0x91, 0x6a, 0xca, 0x2a, 0x7c, 0x60, 0xf7, 0x22, 0xa5, 0x4e,
	0x5b, 0x01, 0x46, 0xec, 0x36, 0x88, 0xe8, 0x99, 0x76, 0x83, 0xbe, 0x0f, 0x77, 0x46, 0x10, 0xaa,
	0x15, 0xb1, 0x00, 0x15, 0xe4, 0xb2, 0x4d, 0x22, 0x7d, 0xe7, 0xb6, 0xb3, 0xdf, 0xeb, 0x1f, 0xc1,
	0x7c, 0xf1, 0xff, 0x48, 0x30, 0x01, 0xc6, 0x77, 0xb7, 0x77, 0xbf, 0xb0, 0x9f, 0xcc, 0xbc, 0x63,
	0x4e, 0x40, 0xb9, 0xb5, 0x7f, 0x34, 0x63, 0xac, 0x7f, 0x0e, 0x4b, 0x23, 0xdf, 0x01, 0x19, 0x65,
	0xb3, 0xdd, 0x9e, 0x79, 0xc7, 0x9c, 0x84, 0xca, 0x57, 0x3b, 0xdb, 0x8f, 0x9b, 0x5b, 0xed, 0xed,
	0x19, 0x83, 0x81, 0xbf, 0x78, 0xbc, 0x37, 0x53, 0xda, 0xfa, 0x18, 0x16, 0x63, 0xd2, 0xd9, 0x40,
	0x5d, 0x66, 0xb1, 0x16, 0x3c, 0xfe, 0x1f, 0x76, 0xb6, 0x66, 0x9f, 0x20, 0x12, 0x1d, 0x88, 0xfd,
	0x9d, 0x4b, 0xa4, 0xbf, 0x31, 0x8c, 0x3f, 0x1b, 0xc6, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93,
	0x04, 0x1c, 0x45, 0x15, 0x24, 0x00, 0x00,
}
